// Code generated by ent, DO NOT EDIT.

package person

import (
	"time"
	"working-time-tracker/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Person {
	return predicate.Person(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Person {
	return predicate.Person(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Person {
	return predicate.Person(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Person {
	return predicate.Person(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Person {
	return predicate.Person(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Person {
	return predicate.Person(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Person {
	return predicate.Person(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldName, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldEmail, v))
}

// OrganizationID applies equality check predicate on the "organization_id" field. It's identical to OrganizationIDEQ.
func OrganizationID(v uuid.UUID) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldOrganizationID, v))
}

// PasswordHash applies equality check predicate on the "password_hash" field. It's identical to PasswordHashEQ.
func PasswordHash(v string) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldPasswordHash, v))
}

// ClerkUserID applies equality check predicate on the "clerk_user_id" field. It's identical to ClerkUserIDEQ.
func ClerkUserID(v string) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldClerkUserID, v))
}

// IsOwner applies equality check predicate on the "is_owner" field. It's identical to IsOwnerEQ.
func IsOwner(v bool) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldIsOwner, v))
}

// WeeklyHours applies equality check predicate on the "weekly_hours" field. It's identical to WeeklyHoursEQ.
func WeeklyHours(v int) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldWeeklyHours, v))
}

// PaymentFrequency applies equality check predicate on the "payment_frequency" field. It's identical to PaymentFrequencyEQ.
func PaymentFrequency(v string) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldPaymentFrequency, v))
}

// PaymentDay applies equality check predicate on the "payment_day" field. It's identical to PaymentDayEQ.
func PaymentDay(v int) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldPaymentDay, v))
}

// PaymentStart applies equality check predicate on the "payment_start" field. It's identical to PaymentStartEQ.
func PaymentStart(v string) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldPaymentStart, v))
}

// OnboardedAt applies equality check predicate on the "onboarded_at" field. It's identical to OnboardedAtEQ.
func OnboardedAt(v time.Time) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldOnboardedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Person {
	return predicate.Person(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Person {
	return predicate.Person(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Person {
	return predicate.Person(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Person {
	return predicate.Person(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Person {
	return predicate.Person(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Person {
	return predicate.Person(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Person {
	return predicate.Person(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Person {
	return predicate.Person(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Person {
	return predicate.Person(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Person {
	return predicate.Person(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Person {
	return predicate.Person(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Person {
	return predicate.Person(sql.FieldContainsFold(FieldName, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Person {
	return predicate.Person(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Person {
	return predicate.Person(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Person {
	return predicate.Person(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Person {
	return predicate.Person(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Person {
	return predicate.Person(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Person {
	return predicate.Person(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Person {
	return predicate.Person(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Person {
	return predicate.Person(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Person {
	return predicate.Person(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Person {
	return predicate.Person(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Person {
	return predicate.Person(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Person {
	return predicate.Person(sql.FieldContainsFold(FieldEmail, v))
}

// OrganizationIDEQ applies the EQ predicate on the "organization_id" field.
func OrganizationIDEQ(v uuid.UUID) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldOrganizationID, v))
}

// OrganizationIDNEQ applies the NEQ predicate on the "organization_id" field.
func OrganizationIDNEQ(v uuid.UUID) predicate.Person {
	return predicate.Person(sql.FieldNEQ(FieldOrganizationID, v))
}

// OrganizationIDIn applies the In predicate on the "organization_id" field.
func OrganizationIDIn(vs ...uuid.UUID) predicate.Person {
	return predicate.Person(sql.FieldIn(FieldOrganizationID, vs...))
}

// OrganizationIDNotIn applies the NotIn predicate on the "organization_id" field.
func OrganizationIDNotIn(vs ...uuid.UUID) predicate.Person {
	return predicate.Person(sql.FieldNotIn(FieldOrganizationID, vs...))
}

// PasswordHashEQ applies the EQ predicate on the "password_hash" field.
func PasswordHashEQ(v string) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldPasswordHash, v))
}

// PasswordHashNEQ applies the NEQ predicate on the "password_hash" field.
func PasswordHashNEQ(v string) predicate.Person {
	return predicate.Person(sql.FieldNEQ(FieldPasswordHash, v))
}

// PasswordHashIn applies the In predicate on the "password_hash" field.
func PasswordHashIn(vs ...string) predicate.Person {
	return predicate.Person(sql.FieldIn(FieldPasswordHash, vs...))
}

// PasswordHashNotIn applies the NotIn predicate on the "password_hash" field.
func PasswordHashNotIn(vs ...string) predicate.Person {
	return predicate.Person(sql.FieldNotIn(FieldPasswordHash, vs...))
}

// PasswordHashGT applies the GT predicate on the "password_hash" field.
func PasswordHashGT(v string) predicate.Person {
	return predicate.Person(sql.FieldGT(FieldPasswordHash, v))
}

// PasswordHashGTE applies the GTE predicate on the "password_hash" field.
func PasswordHashGTE(v string) predicate.Person {
	return predicate.Person(sql.FieldGTE(FieldPasswordHash, v))
}

// PasswordHashLT applies the LT predicate on the "password_hash" field.
func PasswordHashLT(v string) predicate.Person {
	return predicate.Person(sql.FieldLT(FieldPasswordHash, v))
}

// PasswordHashLTE applies the LTE predicate on the "password_hash" field.
func PasswordHashLTE(v string) predicate.Person {
	return predicate.Person(sql.FieldLTE(FieldPasswordHash, v))
}

// PasswordHashContains applies the Contains predicate on the "password_hash" field.
func PasswordHashContains(v string) predicate.Person {
	return predicate.Person(sql.FieldContains(FieldPasswordHash, v))
}

// PasswordHashHasPrefix applies the HasPrefix predicate on the "password_hash" field.
func PasswordHashHasPrefix(v string) predicate.Person {
	return predicate.Person(sql.FieldHasPrefix(FieldPasswordHash, v))
}

// PasswordHashHasSuffix applies the HasSuffix predicate on the "password_hash" field.
func PasswordHashHasSuffix(v string) predicate.Person {
	return predicate.Person(sql.FieldHasSuffix(FieldPasswordHash, v))
}

// PasswordHashIsNil applies the IsNil predicate on the "password_hash" field.
func PasswordHashIsNil() predicate.Person {
	return predicate.Person(sql.FieldIsNull(FieldPasswordHash))
}

// PasswordHashNotNil applies the NotNil predicate on the "password_hash" field.
func PasswordHashNotNil() predicate.Person {
	return predicate.Person(sql.FieldNotNull(FieldPasswordHash))
}

// PasswordHashEqualFold applies the EqualFold predicate on the "password_hash" field.
func PasswordHashEqualFold(v string) predicate.Person {
	return predicate.Person(sql.FieldEqualFold(FieldPasswordHash, v))
}

// PasswordHashContainsFold applies the ContainsFold predicate on the "password_hash" field.
func PasswordHashContainsFold(v string) predicate.Person {
	return predicate.Person(sql.FieldContainsFold(FieldPasswordHash, v))
}

// ClerkUserIDEQ applies the EQ predicate on the "clerk_user_id" field.
func ClerkUserIDEQ(v string) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldClerkUserID, v))
}

// ClerkUserIDNEQ applies the NEQ predicate on the "clerk_user_id" field.
func ClerkUserIDNEQ(v string) predicate.Person {
	return predicate.Person(sql.FieldNEQ(FieldClerkUserID, v))
}

// ClerkUserIDIn applies the In predicate on the "clerk_user_id" field.
func ClerkUserIDIn(vs ...string) predicate.Person {
	return predicate.Person(sql.FieldIn(FieldClerkUserID, vs...))
}

// ClerkUserIDNotIn applies the NotIn predicate on the "clerk_user_id" field.
func ClerkUserIDNotIn(vs ...string) predicate.Person {
	return predicate.Person(sql.FieldNotIn(FieldClerkUserID, vs...))
}

// ClerkUserIDGT applies the GT predicate on the "clerk_user_id" field.
func ClerkUserIDGT(v string) predicate.Person {
	return predicate.Person(sql.FieldGT(FieldClerkUserID, v))
}

// ClerkUserIDGTE applies the GTE predicate on the "clerk_user_id" field.
func ClerkUserIDGTE(v string) predicate.Person {
	return predicate.Person(sql.FieldGTE(FieldClerkUserID, v))
}

// ClerkUserIDLT applies the LT predicate on the "clerk_user_id" field.
func ClerkUserIDLT(v string) predicate.Person {
	return predicate.Person(sql.FieldLT(FieldClerkUserID, v))
}

// ClerkUserIDLTE applies the LTE predicate on the "clerk_user_id" field.
func ClerkUserIDLTE(v string) predicate.Person {
	return predicate.Person(sql.FieldLTE(FieldClerkUserID, v))
}

// ClerkUserIDContains applies the Contains predicate on the "clerk_user_id" field.
func ClerkUserIDContains(v string) predicate.Person {
	return predicate.Person(sql.FieldContains(FieldClerkUserID, v))
}

// ClerkUserIDHasPrefix applies the HasPrefix predicate on the "clerk_user_id" field.
func ClerkUserIDHasPrefix(v string) predicate.Person {
	return predicate.Person(sql.FieldHasPrefix(FieldClerkUserID, v))
}

// ClerkUserIDHasSuffix applies the HasSuffix predicate on the "clerk_user_id" field.
func ClerkUserIDHasSuffix(v string) predicate.Person {
	return predicate.Person(sql.FieldHasSuffix(FieldClerkUserID, v))
}

// ClerkUserIDIsNil applies the IsNil predicate on the "clerk_user_id" field.
func ClerkUserIDIsNil() predicate.Person {
	return predicate.Person(sql.FieldIsNull(FieldClerkUserID))
}

// ClerkUserIDNotNil applies the NotNil predicate on the "clerk_user_id" field.
func ClerkUserIDNotNil() predicate.Person {
	return predicate.Person(sql.FieldNotNull(FieldClerkUserID))
}

// ClerkUserIDEqualFold applies the EqualFold predicate on the "clerk_user_id" field.
func ClerkUserIDEqualFold(v string) predicate.Person {
	return predicate.Person(sql.FieldEqualFold(FieldClerkUserID, v))
}

// ClerkUserIDContainsFold applies the ContainsFold predicate on the "clerk_user_id" field.
func ClerkUserIDContainsFold(v string) predicate.Person {
	return predicate.Person(sql.FieldContainsFold(FieldClerkUserID, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v Role) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v Role) predicate.Person {
	return predicate.Person(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...Role) predicate.Person {
	return predicate.Person(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...Role) predicate.Person {
	return predicate.Person(sql.FieldNotIn(FieldRole, vs...))
}

// IsOwnerEQ applies the EQ predicate on the "is_owner" field.
func IsOwnerEQ(v bool) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldIsOwner, v))
}

// IsOwnerNEQ applies the NEQ predicate on the "is_owner" field.
func IsOwnerNEQ(v bool) predicate.Person {
	return predicate.Person(sql.FieldNEQ(FieldIsOwner, v))
}

// WeeklyHoursEQ applies the EQ predicate on the "weekly_hours" field.
func WeeklyHoursEQ(v int) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldWeeklyHours, v))
}

// WeeklyHoursNEQ applies the NEQ predicate on the "weekly_hours" field.
func WeeklyHoursNEQ(v int) predicate.Person {
	return predicate.Person(sql.FieldNEQ(FieldWeeklyHours, v))
}

// WeeklyHoursIn applies the In predicate on the "weekly_hours" field.
func WeeklyHoursIn(vs ...int) predicate.Person {
	return predicate.Person(sql.FieldIn(FieldWeeklyHours, vs...))
}

// WeeklyHoursNotIn applies the NotIn predicate on the "weekly_hours" field.
func WeeklyHoursNotIn(vs ...int) predicate.Person {
	return predicate.Person(sql.FieldNotIn(FieldWeeklyHours, vs...))
}

// WeeklyHoursGT applies the GT predicate on the "weekly_hours" field.
func WeeklyHoursGT(v int) predicate.Person {
	return predicate.Person(sql.FieldGT(FieldWeeklyHours, v))
}

// WeeklyHoursGTE applies the GTE predicate on the "weekly_hours" field.
func WeeklyHoursGTE(v int) predicate.Person {
	return predicate.Person(sql.FieldGTE(FieldWeeklyHours, v))
}

// WeeklyHoursLT applies the LT predicate on the "weekly_hours" field.
func WeeklyHoursLT(v int) predicate.Person {
	return predicate.Person(sql.FieldLT(FieldWeeklyHours, v))
}

// WeeklyHoursLTE applies the LTE predicate on the "weekly_hours" field.
func WeeklyHoursLTE(v int) predicate.Person {
	return predicate.Person(sql.FieldLTE(FieldWeeklyHours, v))
}

// WeeklyHoursIsNil applies the IsNil predicate on the "weekly_hours" field.
func WeeklyHoursIsNil() predicate.Person {
	return predicate.Person(sql.FieldIsNull(FieldWeeklyHours))
}

// WeeklyHoursNotNil applies the NotNil predicate on the "weekly_hours" field.
func WeeklyHoursNotNil() predicate.Person {
	return predicate.Person(sql.FieldNotNull(FieldWeeklyHours))
}

// PaymentFrequencyEQ applies the EQ predicate on the "payment_frequency" field.
func PaymentFrequencyEQ(v string) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldPaymentFrequency, v))
}

// PaymentFrequencyNEQ applies the NEQ predicate on the "payment_frequency" field.
func PaymentFrequencyNEQ(v string) predicate.Person {
	return predicate.Person(sql.FieldNEQ(FieldPaymentFrequency, v))
}

// PaymentFrequencyIn applies the In predicate on the "payment_frequency" field.
func PaymentFrequencyIn(vs ...string) predicate.Person {
	return predicate.Person(sql.FieldIn(FieldPaymentFrequency, vs...))
}

// PaymentFrequencyNotIn applies the NotIn predicate on the "payment_frequency" field.
func PaymentFrequencyNotIn(vs ...string) predicate.Person {
	return predicate.Person(sql.FieldNotIn(FieldPaymentFrequency, vs...))
}

// PaymentFrequencyGT applies the GT predicate on the "payment_frequency" field.
func PaymentFrequencyGT(v string) predicate.Person {
	return predicate.Person(sql.FieldGT(FieldPaymentFrequency, v))
}

// PaymentFrequencyGTE applies the GTE predicate on the "payment_frequency" field.
func PaymentFrequencyGTE(v string) predicate.Person {
	return predicate.Person(sql.FieldGTE(FieldPaymentFrequency, v))
}

// PaymentFrequencyLT applies the LT predicate on the "payment_frequency" field.
func PaymentFrequencyLT(v string) predicate.Person {
	return predicate.Person(sql.FieldLT(FieldPaymentFrequency, v))
}

// PaymentFrequencyLTE applies the LTE predicate on the "payment_frequency" field.
func PaymentFrequencyLTE(v string) predicate.Person {
	return predicate.Person(sql.FieldLTE(FieldPaymentFrequency, v))
}

// PaymentFrequencyContains applies the Contains predicate on the "payment_frequency" field.
func PaymentFrequencyContains(v string) predicate.Person {
	return predicate.Person(sql.FieldContains(FieldPaymentFrequency, v))
}

// PaymentFrequencyHasPrefix applies the HasPrefix predicate on the "payment_frequency" field.
func PaymentFrequencyHasPrefix(v string) predicate.Person {
	return predicate.Person(sql.FieldHasPrefix(FieldPaymentFrequency, v))
}

// PaymentFrequencyHasSuffix applies the HasSuffix predicate on the "payment_frequency" field.
func PaymentFrequencyHasSuffix(v string) predicate.Person {
	return predicate.Person(sql.FieldHasSuffix(FieldPaymentFrequency, v))
}

// PaymentFrequencyIsNil applies the IsNil predicate on the "payment_frequency" field.
func PaymentFrequencyIsNil() predicate.Person {
	return predicate.Person(sql.FieldIsNull(FieldPaymentFrequency))
}

// PaymentFrequencyNotNil applies the NotNil predicate on the "payment_frequency" field.
func PaymentFrequencyNotNil() predicate.Person {
	return predicate.Person(sql.FieldNotNull(FieldPaymentFrequency))
}

// PaymentFrequencyEqualFold applies the EqualFold predicate on the "payment_frequency" field.
func PaymentFrequencyEqualFold(v string) predicate.Person {
	return predicate.Person(sql.FieldEqualFold(FieldPaymentFrequency, v))
}

// PaymentFrequencyContainsFold applies the ContainsFold predicate on the "payment_frequency" field.
func PaymentFrequencyContainsFold(v string) predicate.Person {
	return predicate.Person(sql.FieldContainsFold(FieldPaymentFrequency, v))
}

// PaymentDayEQ applies the EQ predicate on the "payment_day" field.
func PaymentDayEQ(v int) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldPaymentDay, v))
}

// PaymentDayNEQ applies the NEQ predicate on the "payment_day" field.
func PaymentDayNEQ(v int) predicate.Person {
	return predicate.Person(sql.FieldNEQ(FieldPaymentDay, v))
}

// PaymentDayIn applies the In predicate on the "payment_day" field.
func PaymentDayIn(vs ...int) predicate.Person {
	return predicate.Person(sql.FieldIn(FieldPaymentDay, vs...))
}

// PaymentDayNotIn applies the NotIn predicate on the "payment_day" field.
func PaymentDayNotIn(vs ...int) predicate.Person {
	return predicate.Person(sql.FieldNotIn(FieldPaymentDay, vs...))
}

// PaymentDayGT applies the GT predicate on the "payment_day" field.
func PaymentDayGT(v int) predicate.Person {
	return predicate.Person(sql.FieldGT(FieldPaymentDay, v))
}

// PaymentDayGTE applies the GTE predicate on the "payment_day" field.
func PaymentDayGTE(v int) predicate.Person {
	return predicate.Person(sql.FieldGTE(FieldPaymentDay, v))
}

// PaymentDayLT applies the LT predicate on the "payment_day" field.
func PaymentDayLT(v int) predicate.Person {
	return predicate.Person(sql.FieldLT(FieldPaymentDay, v))
}

// PaymentDayLTE applies the LTE predicate on the "payment_day" field.
func PaymentDayLTE(v int) predicate.Person {
	return predicate.Person(sql.FieldLTE(FieldPaymentDay, v))
}

// PaymentDayIsNil applies the IsNil predicate on the "payment_day" field.
func PaymentDayIsNil() predicate.Person {
	return predicate.Person(sql.FieldIsNull(FieldPaymentDay))
}

// PaymentDayNotNil applies the NotNil predicate on the "payment_day" field.
func PaymentDayNotNil() predicate.Person {
	return predicate.Person(sql.FieldNotNull(FieldPaymentDay))
}

// PaymentStartEQ applies the EQ predicate on the "payment_start" field.
func PaymentStartEQ(v string) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldPaymentStart, v))
}

// PaymentStartNEQ applies the NEQ predicate on the "payment_start" field.
func PaymentStartNEQ(v string) predicate.Person {
	return predicate.Person(sql.FieldNEQ(FieldPaymentStart, v))
}

// PaymentStartIn applies the In predicate on the "payment_start" field.
func PaymentStartIn(vs ...string) predicate.Person {
	return predicate.Person(sql.FieldIn(FieldPaymentStart, vs...))
}

// PaymentStartNotIn applies the NotIn predicate on the "payment_start" field.
func PaymentStartNotIn(vs ...string) predicate.Person {
	return predicate.Person(sql.FieldNotIn(FieldPaymentStart, vs...))
}

// PaymentStartGT applies the GT predicate on the "payment_start" field.
func PaymentStartGT(v string) predicate.Person {
	return predicate.Person(sql.FieldGT(FieldPaymentStart, v))
}

// PaymentStartGTE applies the GTE predicate on the "payment_start" field.
func PaymentStartGTE(v string) predicate.Person {
	return predicate.Person(sql.FieldGTE(FieldPaymentStart, v))
}

// PaymentStartLT applies the LT predicate on the "payment_start" field.
func PaymentStartLT(v string) predicate.Person {
	return predicate.Person(sql.FieldLT(FieldPaymentStart, v))
}

// PaymentStartLTE applies the LTE predicate on the "payment_start" field.
func PaymentStartLTE(v string) predicate.Person {
	return predicate.Person(sql.FieldLTE(FieldPaymentStart, v))
}

// PaymentStartContains applies the Contains predicate on the "payment_start" field.
func PaymentStartContains(v string) predicate.Person {
	return predicate.Person(sql.FieldContains(FieldPaymentStart, v))
}

// PaymentStartHasPrefix applies the HasPrefix predicate on the "payment_start" field.
func PaymentStartHasPrefix(v string) predicate.Person {
	return predicate.Person(sql.FieldHasPrefix(FieldPaymentStart, v))
}

// PaymentStartHasSuffix applies the HasSuffix predicate on the "payment_start" field.
func PaymentStartHasSuffix(v string) predicate.Person {
	return predicate.Person(sql.FieldHasSuffix(FieldPaymentStart, v))
}

// PaymentStartIsNil applies the IsNil predicate on the "payment_start" field.
func PaymentStartIsNil() predicate.Person {
	return predicate.Person(sql.FieldIsNull(FieldPaymentStart))
}

// PaymentStartNotNil applies the NotNil predicate on the "payment_start" field.
func PaymentStartNotNil() predicate.Person {
	return predicate.Person(sql.FieldNotNull(FieldPaymentStart))
}

// PaymentStartEqualFold applies the EqualFold predicate on the "payment_start" field.
func PaymentStartEqualFold(v string) predicate.Person {
	return predicate.Person(sql.FieldEqualFold(FieldPaymentStart, v))
}

// PaymentStartContainsFold applies the ContainsFold predicate on the "payment_start" field.
func PaymentStartContainsFold(v string) predicate.Person {
	return predicate.Person(sql.FieldContainsFold(FieldPaymentStart, v))
}

// OnboardedAtEQ applies the EQ predicate on the "onboarded_at" field.
func OnboardedAtEQ(v time.Time) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldOnboardedAt, v))
}

// OnboardedAtNEQ applies the NEQ predicate on the "onboarded_at" field.
func OnboardedAtNEQ(v time.Time) predicate.Person {
	return predicate.Person(sql.FieldNEQ(FieldOnboardedAt, v))
}

// OnboardedAtIn applies the In predicate on the "onboarded_at" field.
func OnboardedAtIn(vs ...time.Time) predicate.Person {
	return predicate.Person(sql.FieldIn(FieldOnboardedAt, vs...))
}

// OnboardedAtNotIn applies the NotIn predicate on the "onboarded_at" field.
func OnboardedAtNotIn(vs ...time.Time) predicate.Person {
	return predicate.Person(sql.FieldNotIn(FieldOnboardedAt, vs...))
}

// OnboardedAtGT applies the GT predicate on the "onboarded_at" field.
func OnboardedAtGT(v time.Time) predicate.Person {
	return predicate.Person(sql.FieldGT(FieldOnboardedAt, v))
}

// OnboardedAtGTE applies the GTE predicate on the "onboarded_at" field.
func OnboardedAtGTE(v time.Time) predicate.Person {
	return predicate.Person(sql.FieldGTE(FieldOnboardedAt, v))
}

// OnboardedAtLT applies the LT predicate on the "onboarded_at" field.
func OnboardedAtLT(v time.Time) predicate.Person {
	return predicate.Person(sql.FieldLT(FieldOnboardedAt, v))
}

// OnboardedAtLTE applies the LTE predicate on the "onboarded_at" field.
func OnboardedAtLTE(v time.Time) predicate.Person {
	return predicate.Person(sql.FieldLTE(FieldOnboardedAt, v))
}

// OnboardedAtIsNil applies the IsNil predicate on the "onboarded_at" field.
func OnboardedAtIsNil() predicate.Person {
	return predicate.Person(sql.FieldIsNull(FieldOnboardedAt))
}

// OnboardedAtNotNil applies the NotNil predicate on the "onboarded_at" field.
func OnboardedAtNotNil() predicate.Person {
	return predicate.Person(sql.FieldNotNull(FieldOnboardedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Person {
	return predicate.Person(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Person {
	return predicate.Person(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Person {
	return predicate.Person(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Person {
	return predicate.Person(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Person {
	return predicate.Person(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Person {
	return predicate.Person(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Person {
	return predicate.Person(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Person {
	return predicate.Person(sql.FieldLTE(FieldCreatedAt, v))
}

// HasOrganization applies the HasEdge predicate on the "organization" edge.
func HasOrganization() predicate.Person {
	return predicate.Person(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrganizationTable, OrganizationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrganizationWith applies the HasEdge predicate on the "organization" edge with a given conditions (other predicates).
func HasOrganizationWith(preds ...predicate.Organization) predicate.Person {
	return predicate.Person(func(s *sql.Selector) {
		step := newOrganizationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTasks applies the HasEdge predicate on the "tasks" edge.
func HasTasks() predicate.Person {
	return predicate.Person(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTasksWith applies the HasEdge predicate on the "tasks" edge with a given conditions (other predicates).
func HasTasksWith(preds ...predicate.Task) predicate.Person {
	return predicate.Person(func(s *sql.Selector) {
		step := newTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeamMemberships applies the HasEdge predicate on the "team_memberships" edge.
func HasTeamMemberships() predicate.Person {
	return predicate.Person(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TeamMembershipsTable, TeamMembershipsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamMembershipsWith applies the HasEdge predicate on the "team_memberships" edge with a given conditions (other predicates).
func HasTeamMembershipsWith(preds ...predicate.TeamMembership) predicate.Person {
	return predicate.Person(func(s *sql.Selector) {
		step := newTeamMembershipsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWorkSessions applies the HasEdge predicate on the "work_sessions" edge.
func HasWorkSessions() predicate.Person {
	return predicate.Person(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WorkSessionsTable, WorkSessionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkSessionsWith applies the HasEdge predicate on the "work_sessions" edge with a given conditions (other predicates).
func HasWorkSessionsWith(preds ...predicate.WorkSession) predicate.Person {
	return predicate.Person(func(s *sql.Selector) {
		step := newWorkSessionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSessions applies the HasEdge predicate on the "sessions" edge.
func HasSessions() predicate.Person {
	return predicate.Person(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionsWith applies the HasEdge predicate on the "sessions" edge with a given conditions (other predicates).
func HasSessionsWith(preds ...predicate.Session) predicate.Person {
	return predicate.Person(func(s *sql.Selector) {
		step := newSessionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCreatedInvites applies the HasEdge predicate on the "created_invites" edge.
func HasCreatedInvites() predicate.Person {
	return predicate.Person(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CreatedInvitesTable, CreatedInvitesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatedInvitesWith applies the HasEdge predicate on the "created_invites" edge with a given conditions (other predicates).
func HasCreatedInvitesWith(preds ...predicate.Invite) predicate.Person {
	return predicate.Person(func(s *sql.Selector) {
		step := newCreatedInvitesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAllocations applies the HasEdge predicate on the "allocations" edge.
func HasAllocations() predicate.Person {
	return predicate.Person(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AllocationsTable, AllocationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAllocationsWith applies the HasEdge predicate on the "allocations" edge with a given conditions (other predicates).
func HasAllocationsWith(preds ...predicate.Allocation) predicate.Person {
	return predicate.Person(func(s *sql.Selector) {
		step := newAllocationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Person) predicate.Person {
	return predicate.Person(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Person) predicate.Person {
	return predicate.Person(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Person) predicate.Person {
	return predicate.Person(sql.NotPredicates(p))
}
