// Code generated by ent, DO NOT EDIT.

package issuesync

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the issuesync type in the database.
	Label = "issue_sync"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIntegrationID holds the string denoting the integration_id field in the database.
	FieldIntegrationID = "integration_id"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldItemID holds the string denoting the item_id field in the database.
	FieldItemID = "item_id"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldLabels holds the string denoting the labels field in the database.
	FieldLabels = "labels"
	// FieldAssigneeLogins holds the string denoting the assignee_logins field in the database.
	FieldAssigneeLogins = "assignee_logins"
	// FieldMappedLogin holds the string denoting the mapped_login field in the database.
	FieldMappedLogin = "mapped_login"
	// FieldMappedPersonID holds the string denoting the mapped_person_id field in the database.
	FieldMappedPersonID = "mapped_person_id"
	// FieldDeadline holds the string denoting the deadline field in the database.
	FieldDeadline = "deadline"
	// FieldStuckSig holds the string denoting the stuck_sig field in the database.
	FieldStuckSig = "stuck_sig"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldSyncedAt holds the string denoting the synced_at field in the database.
	FieldSyncedAt = "synced_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeIntegration holds the string denoting the integration edge name in mutations.
	EdgeIntegration = "integration"
	// EdgeTask holds the string denoting the task edge name in mutations.
	EdgeTask = "task"
	// Table holds the table name of the issuesync in the database.
	Table = "issue_syncs"
	// IntegrationTable is the table that holds the integration relation/edge.
	IntegrationTable = "issue_syncs"
	// IntegrationInverseTable is the table name for the Integration entity.
	// It exists in this package in order to avoid circular dependency with the "integration" package.
	IntegrationInverseTable = "integrations"
	// IntegrationColumn is the table column denoting the integration relation/edge.
	IntegrationColumn = "integration_id"
	// TaskTable is the table that holds the task relation/edge.
	TaskTable = "issue_syncs"
	// TaskInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TaskInverseTable = "tasks"
	// TaskColumn is the table column denoting the task relation/edge.
	TaskColumn = "task_id"
)

// Columns holds all SQL columns for issuesync fields.
var Columns = []string{
	FieldID,
	FieldIntegrationID,
	FieldTaskID,
	FieldItemID,
	FieldURL,
	FieldState,
	FieldTitle,
	FieldBody,
	FieldLabels,
	FieldAssigneeLogins,
	FieldMappedLogin,
	FieldMappedPersonID,
	FieldDeadline,
	FieldStuckSig,
	FieldLastError,
	FieldSyncedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultURL holds the default value on creation for the "url" field.
	DefaultURL string
	// DefaultTitle holds the default value on creation for the "title" field.
	DefaultTitle string
	// DefaultBody holds the default value on creation for the "body" field.
	DefaultBody string
	// DefaultMappedLogin holds the default value on creation for the "mapped_login" field.
	DefaultMappedLogin string
	// DefaultStuckSig holds the default value on creation for the "stuck_sig" field.
	DefaultStuckSig string
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// DefaultSyncedAt holds the default value on creation for the "synced_at" field.
	DefaultSyncedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// State defines the type for the "state" enum field.
type State string

// StateOpen is the default value of the State enum.
const DefaultState = StateOpen

// State values.
const (
	StateOpen    State = "open"
	StateClosed  State = "closed"
	StateGone    State = "gone"
	StatePending State = "pending"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateOpen, StateClosed, StateGone, StatePending:
		return nil
	default:
		return fmt.Errorf("issuesync: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the IssueSync queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIntegrationID orders the results by the integration_id field.
func ByIntegrationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntegrationID, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByItemID orders the results by the item_id field.
func ByItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemID, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByBody orders the results by the body field.
func ByBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBody, opts...).ToFunc()
}

// ByMappedLogin orders the results by the mapped_login field.
func ByMappedLogin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMappedLogin, opts...).ToFunc()
}

// ByMappedPersonID orders the results by the mapped_person_id field.
func ByMappedPersonID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMappedPersonID, opts...).ToFunc()
}

// ByDeadline orders the results by the deadline field.
func ByDeadline(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeadline, opts...).ToFunc()
}

// ByStuckSig orders the results by the stuck_sig field.
func ByStuckSig(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStuckSig, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// BySyncedAt orders the results by the synced_at field.
func BySyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByIntegrationField orders the results by integration field.
func ByIntegrationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIntegrationStep(), sql.OrderByField(field, opts...))
	}
}

// ByTaskField orders the results by task field.
func ByTaskField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskStep(), sql.OrderByField(field, opts...))
	}
}
func newIntegrationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IntegrationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, IntegrationTable, IntegrationColumn),
	)
}
func newTaskStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
	)
}
