// Code generated by ent, DO NOT EDIT.

package issuesync

import (
	"time"
	"working-time-tracker/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLTE(FieldID, id))
}

// IntegrationID applies equality check predicate on the "integration_id" field. It's identical to IntegrationIDEQ.
func IntegrationID(v uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldIntegrationID, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldTaskID, v))
}

// ItemID applies equality check predicate on the "item_id" field. It's identical to ItemIDEQ.
func ItemID(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldItemID, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldURL, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldTitle, v))
}

// Body applies equality check predicate on the "body" field. It's identical to BodyEQ.
func Body(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldBody, v))
}

// MappedLogin applies equality check predicate on the "mapped_login" field. It's identical to MappedLoginEQ.
func MappedLogin(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldMappedLogin, v))
}

// MappedPersonID applies equality check predicate on the "mapped_person_id" field. It's identical to MappedPersonIDEQ.
func MappedPersonID(v uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldMappedPersonID, v))
}

// Deadline applies equality check predicate on the "deadline" field. It's identical to DeadlineEQ.
func Deadline(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldDeadline, v))
}

// StuckSig applies equality check predicate on the "stuck_sig" field. It's identical to StuckSigEQ.
func StuckSig(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldStuckSig, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldLastError, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldSyncedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldCreatedAt, v))
}

// IntegrationIDEQ applies the EQ predicate on the "integration_id" field.
func IntegrationIDEQ(v uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldIntegrationID, v))
}

// IntegrationIDNEQ applies the NEQ predicate on the "integration_id" field.
func IntegrationIDNEQ(v uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNEQ(FieldIntegrationID, v))
}

// IntegrationIDIn applies the In predicate on the "integration_id" field.
func IntegrationIDIn(vs ...uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIn(FieldIntegrationID, vs...))
}

// IntegrationIDNotIn applies the NotIn predicate on the "integration_id" field.
func IntegrationIDNotIn(vs ...uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotIn(FieldIntegrationID, vs...))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDIsNil applies the IsNil predicate on the "task_id" field.
func TaskIDIsNil() predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIsNull(FieldTaskID))
}

// TaskIDNotNil applies the NotNil predicate on the "task_id" field.
func TaskIDNotNil() predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotNull(FieldTaskID))
}

// ItemIDEQ applies the EQ predicate on the "item_id" field.
func ItemIDEQ(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldItemID, v))
}

// ItemIDNEQ applies the NEQ predicate on the "item_id" field.
func ItemIDNEQ(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNEQ(FieldItemID, v))
}

// ItemIDIn applies the In predicate on the "item_id" field.
func ItemIDIn(vs ...string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIn(FieldItemID, vs...))
}

// ItemIDNotIn applies the NotIn predicate on the "item_id" field.
func ItemIDNotIn(vs ...string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotIn(FieldItemID, vs...))
}

// ItemIDGT applies the GT predicate on the "item_id" field.
func ItemIDGT(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGT(FieldItemID, v))
}

// ItemIDGTE applies the GTE predicate on the "item_id" field.
func ItemIDGTE(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGTE(FieldItemID, v))
}

// ItemIDLT applies the LT predicate on the "item_id" field.
func ItemIDLT(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLT(FieldItemID, v))
}

// ItemIDLTE applies the LTE predicate on the "item_id" field.
func ItemIDLTE(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLTE(FieldItemID, v))
}

// ItemIDContains applies the Contains predicate on the "item_id" field.
func ItemIDContains(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldContains(FieldItemID, v))
}

// ItemIDHasPrefix applies the HasPrefix predicate on the "item_id" field.
func ItemIDHasPrefix(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldHasPrefix(FieldItemID, v))
}

// ItemIDHasSuffix applies the HasSuffix predicate on the "item_id" field.
func ItemIDHasSuffix(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldHasSuffix(FieldItemID, v))
}

// ItemIDEqualFold applies the EqualFold predicate on the "item_id" field.
func ItemIDEqualFold(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEqualFold(FieldItemID, v))
}

// ItemIDContainsFold applies the ContainsFold predicate on the "item_id" field.
func ItemIDContainsFold(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldContainsFold(FieldItemID, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldContainsFold(FieldURL, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotIn(FieldState, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldContainsFold(FieldTitle, v))
}

// BodyEQ applies the EQ predicate on the "body" field.
func BodyEQ(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldBody, v))
}

// BodyNEQ applies the NEQ predicate on the "body" field.
func BodyNEQ(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNEQ(FieldBody, v))
}

// BodyIn applies the In predicate on the "body" field.
func BodyIn(vs ...string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIn(FieldBody, vs...))
}

// BodyNotIn applies the NotIn predicate on the "body" field.
func BodyNotIn(vs ...string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotIn(FieldBody, vs...))
}

// BodyGT applies the GT predicate on the "body" field.
func BodyGT(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGT(FieldBody, v))
}

// BodyGTE applies the GTE predicate on the "body" field.
func BodyGTE(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGTE(FieldBody, v))
}

// BodyLT applies the LT predicate on the "body" field.
func BodyLT(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLT(FieldBody, v))
}

// BodyLTE applies the LTE predicate on the "body" field.
func BodyLTE(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLTE(FieldBody, v))
}

// BodyContains applies the Contains predicate on the "body" field.
func BodyContains(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldContains(FieldBody, v))
}

// BodyHasPrefix applies the HasPrefix predicate on the "body" field.
func BodyHasPrefix(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldHasPrefix(FieldBody, v))
}

// BodyHasSuffix applies the HasSuffix predicate on the "body" field.
func BodyHasSuffix(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldHasSuffix(FieldBody, v))
}

// BodyEqualFold applies the EqualFold predicate on the "body" field.
func BodyEqualFold(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEqualFold(FieldBody, v))
}

// BodyContainsFold applies the ContainsFold predicate on the "body" field.
func BodyContainsFold(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldContainsFold(FieldBody, v))
}

// LabelsIsNil applies the IsNil predicate on the "labels" field.
func LabelsIsNil() predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIsNull(FieldLabels))
}

// LabelsNotNil applies the NotNil predicate on the "labels" field.
func LabelsNotNil() predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotNull(FieldLabels))
}

// AssigneeLoginsIsNil applies the IsNil predicate on the "assignee_logins" field.
func AssigneeLoginsIsNil() predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIsNull(FieldAssigneeLogins))
}

// AssigneeLoginsNotNil applies the NotNil predicate on the "assignee_logins" field.
func AssigneeLoginsNotNil() predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotNull(FieldAssigneeLogins))
}

// MappedLoginEQ applies the EQ predicate on the "mapped_login" field.
func MappedLoginEQ(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldMappedLogin, v))
}

// MappedLoginNEQ applies the NEQ predicate on the "mapped_login" field.
func MappedLoginNEQ(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNEQ(FieldMappedLogin, v))
}

// MappedLoginIn applies the In predicate on the "mapped_login" field.
func MappedLoginIn(vs ...string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIn(FieldMappedLogin, vs...))
}

// MappedLoginNotIn applies the NotIn predicate on the "mapped_login" field.
func MappedLoginNotIn(vs ...string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotIn(FieldMappedLogin, vs...))
}

// MappedLoginGT applies the GT predicate on the "mapped_login" field.
func MappedLoginGT(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGT(FieldMappedLogin, v))
}

// MappedLoginGTE applies the GTE predicate on the "mapped_login" field.
func MappedLoginGTE(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGTE(FieldMappedLogin, v))
}

// MappedLoginLT applies the LT predicate on the "mapped_login" field.
func MappedLoginLT(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLT(FieldMappedLogin, v))
}

// MappedLoginLTE applies the LTE predicate on the "mapped_login" field.
func MappedLoginLTE(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLTE(FieldMappedLogin, v))
}

// MappedLoginContains applies the Contains predicate on the "mapped_login" field.
func MappedLoginContains(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldContains(FieldMappedLogin, v))
}

// MappedLoginHasPrefix applies the HasPrefix predicate on the "mapped_login" field.
func MappedLoginHasPrefix(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldHasPrefix(FieldMappedLogin, v))
}

// MappedLoginHasSuffix applies the HasSuffix predicate on the "mapped_login" field.
func MappedLoginHasSuffix(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldHasSuffix(FieldMappedLogin, v))
}

// MappedLoginEqualFold applies the EqualFold predicate on the "mapped_login" field.
func MappedLoginEqualFold(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEqualFold(FieldMappedLogin, v))
}

// MappedLoginContainsFold applies the ContainsFold predicate on the "mapped_login" field.
func MappedLoginContainsFold(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldContainsFold(FieldMappedLogin, v))
}

// MappedPersonIDEQ applies the EQ predicate on the "mapped_person_id" field.
func MappedPersonIDEQ(v uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldMappedPersonID, v))
}

// MappedPersonIDNEQ applies the NEQ predicate on the "mapped_person_id" field.
func MappedPersonIDNEQ(v uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNEQ(FieldMappedPersonID, v))
}

// MappedPersonIDIn applies the In predicate on the "mapped_person_id" field.
func MappedPersonIDIn(vs ...uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIn(FieldMappedPersonID, vs...))
}

// MappedPersonIDNotIn applies the NotIn predicate on the "mapped_person_id" field.
func MappedPersonIDNotIn(vs ...uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotIn(FieldMappedPersonID, vs...))
}

// MappedPersonIDGT applies the GT predicate on the "mapped_person_id" field.
func MappedPersonIDGT(v uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGT(FieldMappedPersonID, v))
}

// MappedPersonIDGTE applies the GTE predicate on the "mapped_person_id" field.
func MappedPersonIDGTE(v uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGTE(FieldMappedPersonID, v))
}

// MappedPersonIDLT applies the LT predicate on the "mapped_person_id" field.
func MappedPersonIDLT(v uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLT(FieldMappedPersonID, v))
}

// MappedPersonIDLTE applies the LTE predicate on the "mapped_person_id" field.
func MappedPersonIDLTE(v uuid.UUID) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLTE(FieldMappedPersonID, v))
}

// MappedPersonIDIsNil applies the IsNil predicate on the "mapped_person_id" field.
func MappedPersonIDIsNil() predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIsNull(FieldMappedPersonID))
}

// MappedPersonIDNotNil applies the NotNil predicate on the "mapped_person_id" field.
func MappedPersonIDNotNil() predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotNull(FieldMappedPersonID))
}

// DeadlineEQ applies the EQ predicate on the "deadline" field.
func DeadlineEQ(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldDeadline, v))
}

// DeadlineNEQ applies the NEQ predicate on the "deadline" field.
func DeadlineNEQ(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNEQ(FieldDeadline, v))
}

// DeadlineIn applies the In predicate on the "deadline" field.
func DeadlineIn(vs ...time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIn(FieldDeadline, vs...))
}

// DeadlineNotIn applies the NotIn predicate on the "deadline" field.
func DeadlineNotIn(vs ...time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotIn(FieldDeadline, vs...))
}

// DeadlineGT applies the GT predicate on the "deadline" field.
func DeadlineGT(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGT(FieldDeadline, v))
}

// DeadlineGTE applies the GTE predicate on the "deadline" field.
func DeadlineGTE(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGTE(FieldDeadline, v))
}

// DeadlineLT applies the LT predicate on the "deadline" field.
func DeadlineLT(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLT(FieldDeadline, v))
}

// DeadlineLTE applies the LTE predicate on the "deadline" field.
func DeadlineLTE(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLTE(FieldDeadline, v))
}

// DeadlineIsNil applies the IsNil predicate on the "deadline" field.
func DeadlineIsNil() predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIsNull(FieldDeadline))
}

// DeadlineNotNil applies the NotNil predicate on the "deadline" field.
func DeadlineNotNil() predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotNull(FieldDeadline))
}

// StuckSigEQ applies the EQ predicate on the "stuck_sig" field.
func StuckSigEQ(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldStuckSig, v))
}

// StuckSigNEQ applies the NEQ predicate on the "stuck_sig" field.
func StuckSigNEQ(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNEQ(FieldStuckSig, v))
}

// StuckSigIn applies the In predicate on the "stuck_sig" field.
func StuckSigIn(vs ...string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIn(FieldStuckSig, vs...))
}

// StuckSigNotIn applies the NotIn predicate on the "stuck_sig" field.
func StuckSigNotIn(vs ...string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotIn(FieldStuckSig, vs...))
}

// StuckSigGT applies the GT predicate on the "stuck_sig" field.
func StuckSigGT(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGT(FieldStuckSig, v))
}

// StuckSigGTE applies the GTE predicate on the "stuck_sig" field.
func StuckSigGTE(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGTE(FieldStuckSig, v))
}

// StuckSigLT applies the LT predicate on the "stuck_sig" field.
func StuckSigLT(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLT(FieldStuckSig, v))
}

// StuckSigLTE applies the LTE predicate on the "stuck_sig" field.
func StuckSigLTE(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLTE(FieldStuckSig, v))
}

// StuckSigContains applies the Contains predicate on the "stuck_sig" field.
func StuckSigContains(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldContains(FieldStuckSig, v))
}

// StuckSigHasPrefix applies the HasPrefix predicate on the "stuck_sig" field.
func StuckSigHasPrefix(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldHasPrefix(FieldStuckSig, v))
}

// StuckSigHasSuffix applies the HasSuffix predicate on the "stuck_sig" field.
func StuckSigHasSuffix(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldHasSuffix(FieldStuckSig, v))
}

// StuckSigEqualFold applies the EqualFold predicate on the "stuck_sig" field.
func StuckSigEqualFold(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEqualFold(FieldStuckSig, v))
}

// StuckSigContainsFold applies the ContainsFold predicate on the "stuck_sig" field.
func StuckSigContainsFold(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldContainsFold(FieldStuckSig, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldContainsFold(FieldLastError, v))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLTE(FieldSyncedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IssueSync {
	return predicate.IssueSync(sql.FieldLTE(FieldCreatedAt, v))
}

// HasIntegration applies the HasEdge predicate on the "integration" edge.
func HasIntegration() predicate.IssueSync {
	return predicate.IssueSync(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IntegrationTable, IntegrationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIntegrationWith applies the HasEdge predicate on the "integration" edge with a given conditions (other predicates).
func HasIntegrationWith(preds ...predicate.Integration) predicate.IssueSync {
	return predicate.IssueSync(func(s *sql.Selector) {
		step := newIntegrationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.IssueSync {
	return predicate.IssueSync(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.Task) predicate.IssueSync {
	return predicate.IssueSync(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IssueSync) predicate.IssueSync {
	return predicate.IssueSync(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IssueSync) predicate.IssueSync {
	return predicate.IssueSync(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IssueSync) predicate.IssueSync {
	return predicate.IssueSync(sql.NotPredicates(p))
}
