// Code generated by ent, DO NOT EDIT.

package worksession

import (
	"time"
	"working-time-tracker/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldID, id))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldProjectID, v))
}

// PersonID applies equality check predicate on the "person_id" field. It's identical to PersonIDEQ.
func PersonID(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldPersonID, v))
}

// StartAt applies equality check predicate on the "start_at" field. It's identical to StartAtEQ.
func StartAt(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldStartAt, v))
}

// EndAt applies equality check predicate on the "end_at" field. It's identical to EndAtEQ.
func EndAt(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldEndAt, v))
}

// PayRateCents applies equality check predicate on the "pay_rate_cents" field. It's identical to PayRateCentsEQ.
func PayRateCents(v int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldPayRateCents, v))
}

// BillRateCents applies equality check predicate on the "bill_rate_cents" field. It's identical to BillRateCentsEQ.
func BillRateCents(v int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldBillRateCents, v))
}

// OwnerHours applies equality check predicate on the "owner_hours" field. It's identical to OwnerHoursEQ.
func OwnerHours(v bool) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldOwnerHours, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldCreatedAt, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldProjectID, vs...))
}

// PersonIDEQ applies the EQ predicate on the "person_id" field.
func PersonIDEQ(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldPersonID, v))
}

// PersonIDNEQ applies the NEQ predicate on the "person_id" field.
func PersonIDNEQ(v uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldPersonID, v))
}

// PersonIDIn applies the In predicate on the "person_id" field.
func PersonIDIn(vs ...uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldPersonID, vs...))
}

// PersonIDNotIn applies the NotIn predicate on the "person_id" field.
func PersonIDNotIn(vs ...uuid.UUID) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldPersonID, vs...))
}

// StartAtEQ applies the EQ predicate on the "start_at" field.
func StartAtEQ(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldStartAt, v))
}

// StartAtNEQ applies the NEQ predicate on the "start_at" field.
func StartAtNEQ(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldStartAt, v))
}

// StartAtIn applies the In predicate on the "start_at" field.
func StartAtIn(vs ...time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldStartAt, vs...))
}

// StartAtNotIn applies the NotIn predicate on the "start_at" field.
func StartAtNotIn(vs ...time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldStartAt, vs...))
}

// StartAtGT applies the GT predicate on the "start_at" field.
func StartAtGT(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldStartAt, v))
}

// StartAtGTE applies the GTE predicate on the "start_at" field.
func StartAtGTE(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldStartAt, v))
}

// StartAtLT applies the LT predicate on the "start_at" field.
func StartAtLT(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldStartAt, v))
}

// StartAtLTE applies the LTE predicate on the "start_at" field.
func StartAtLTE(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldStartAt, v))
}

// EndAtEQ applies the EQ predicate on the "end_at" field.
func EndAtEQ(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldEndAt, v))
}

// EndAtNEQ applies the NEQ predicate on the "end_at" field.
func EndAtNEQ(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldEndAt, v))
}

// EndAtIn applies the In predicate on the "end_at" field.
func EndAtIn(vs ...time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldEndAt, vs...))
}

// EndAtNotIn applies the NotIn predicate on the "end_at" field.
func EndAtNotIn(vs ...time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldEndAt, vs...))
}

// EndAtGT applies the GT predicate on the "end_at" field.
func EndAtGT(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldEndAt, v))
}

// EndAtGTE applies the GTE predicate on the "end_at" field.
func EndAtGTE(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldEndAt, v))
}

// EndAtLT applies the LT predicate on the "end_at" field.
func EndAtLT(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldEndAt, v))
}

// EndAtLTE applies the LTE predicate on the "end_at" field.
func EndAtLTE(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldEndAt, v))
}

// EndAtIsNil applies the IsNil predicate on the "end_at" field.
func EndAtIsNil() predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIsNull(FieldEndAt))
}

// EndAtNotNil applies the NotNil predicate on the "end_at" field.
func EndAtNotNil() predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotNull(FieldEndAt))
}

// PayRateCentsEQ applies the EQ predicate on the "pay_rate_cents" field.
func PayRateCentsEQ(v int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldPayRateCents, v))
}

// PayRateCentsNEQ applies the NEQ predicate on the "pay_rate_cents" field.
func PayRateCentsNEQ(v int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldPayRateCents, v))
}

// PayRateCentsIn applies the In predicate on the "pay_rate_cents" field.
func PayRateCentsIn(vs ...int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldPayRateCents, vs...))
}

// PayRateCentsNotIn applies the NotIn predicate on the "pay_rate_cents" field.
func PayRateCentsNotIn(vs ...int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldPayRateCents, vs...))
}

// PayRateCentsGT applies the GT predicate on the "pay_rate_cents" field.
func PayRateCentsGT(v int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldPayRateCents, v))
}

// PayRateCentsGTE applies the GTE predicate on the "pay_rate_cents" field.
func PayRateCentsGTE(v int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldPayRateCents, v))
}

// PayRateCentsLT applies the LT predicate on the "pay_rate_cents" field.
func PayRateCentsLT(v int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldPayRateCents, v))
}

// PayRateCentsLTE applies the LTE predicate on the "pay_rate_cents" field.
func PayRateCentsLTE(v int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldPayRateCents, v))
}

// PayRateCentsIsNil applies the IsNil predicate on the "pay_rate_cents" field.
func PayRateCentsIsNil() predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIsNull(FieldPayRateCents))
}

// PayRateCentsNotNil applies the NotNil predicate on the "pay_rate_cents" field.
func PayRateCentsNotNil() predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotNull(FieldPayRateCents))
}

// BillRateCentsEQ applies the EQ predicate on the "bill_rate_cents" field.
func BillRateCentsEQ(v int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldBillRateCents, v))
}

// BillRateCentsNEQ applies the NEQ predicate on the "bill_rate_cents" field.
func BillRateCentsNEQ(v int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldBillRateCents, v))
}

// BillRateCentsIn applies the In predicate on the "bill_rate_cents" field.
func BillRateCentsIn(vs ...int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldBillRateCents, vs...))
}

// BillRateCentsNotIn applies the NotIn predicate on the "bill_rate_cents" field.
func BillRateCentsNotIn(vs ...int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldBillRateCents, vs...))
}

// BillRateCentsGT applies the GT predicate on the "bill_rate_cents" field.
func BillRateCentsGT(v int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldBillRateCents, v))
}

// BillRateCentsGTE applies the GTE predicate on the "bill_rate_cents" field.
func BillRateCentsGTE(v int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldBillRateCents, v))
}

// BillRateCentsLT applies the LT predicate on the "bill_rate_cents" field.
func BillRateCentsLT(v int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldBillRateCents, v))
}

// BillRateCentsLTE applies the LTE predicate on the "bill_rate_cents" field.
func BillRateCentsLTE(v int) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldBillRateCents, v))
}

// BillRateCentsIsNil applies the IsNil predicate on the "bill_rate_cents" field.
func BillRateCentsIsNil() predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIsNull(FieldBillRateCents))
}

// BillRateCentsNotNil applies the NotNil predicate on the "bill_rate_cents" field.
func BillRateCentsNotNil() predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotNull(FieldBillRateCents))
}

// OwnerHoursEQ applies the EQ predicate on the "owner_hours" field.
func OwnerHoursEQ(v bool) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldOwnerHours, v))
}

// OwnerHoursNEQ applies the NEQ predicate on the "owner_hours" field.
func OwnerHoursNEQ(v bool) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldOwnerHours, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkSession {
	return predicate.WorkSession(sql.FieldLTE(FieldCreatedAt, v))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.WorkSession {
	return predicate.WorkSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.WorkSession {
	return predicate.WorkSession(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPerson applies the HasEdge predicate on the "person" edge.
func HasPerson() predicate.WorkSession {
	return predicate.WorkSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PersonTable, PersonColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPersonWith applies the HasEdge predicate on the "person" edge with a given conditions (other predicates).
func HasPersonWith(preds ...predicate.Person) predicate.WorkSession {
	return predicate.WorkSession(func(s *sql.Selector) {
		step := newPersonStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTaskLinks applies the HasEdge predicate on the "task_links" edge.
func HasTaskLinks() predicate.WorkSession {
	return predicate.WorkSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TaskLinksTable, TaskLinksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskLinksWith applies the HasEdge predicate on the "task_links" edge with a given conditions (other predicates).
func HasTaskLinksWith(preds ...predicate.WorkSessionTask) predicate.WorkSession {
	return predicate.WorkSession(func(s *sql.Selector) {
		step := newTaskLinksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkSession) predicate.WorkSession {
	return predicate.WorkSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkSession) predicate.WorkSession {
	return predicate.WorkSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkSession) predicate.WorkSession {
	return predicate.WorkSession(sql.NotPredicates(p))
}
