// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"working-time-tracker/ent/customer"
	"working-time-tracker/ent/organization"
	"working-time-tracker/ent/predicate"
	"working-time-tracker/ent/project"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CustomerUpdate is the builder for updating Customer entities.
type CustomerUpdate struct {
	config
	hooks    []Hook
	mutation *CustomerMutation
}

// Where appends a list predicates to the CustomerUpdate builder.
func (_u *CustomerUpdate) Where(ps ...predicate.Customer) *CustomerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *CustomerUpdate) SetOrganizationID(v uuid.UUID) *CustomerUpdate {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *CustomerUpdate) SetNillableOrganizationID(v *uuid.UUID) *CustomerUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CustomerUpdate) SetName(v string) *CustomerUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CustomerUpdate) SetNillableName(v *string) *CustomerUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDocument sets the "document" field.
func (_u *CustomerUpdate) SetDocument(v string) *CustomerUpdate {
	_u.mutation.SetDocument(v)
	return _u
}

// SetNillableDocument sets the "document" field if the given value is not nil.
func (_u *CustomerUpdate) SetNillableDocument(v *string) *CustomerUpdate {
	if v != nil {
		_u.SetDocument(*v)
	}
	return _u
}

// ClearDocument clears the value of the "document" field.
func (_u *CustomerUpdate) ClearDocument() *CustomerUpdate {
	_u.mutation.ClearDocument()
	return _u
}

// SetContactName sets the "contact_name" field.
func (_u *CustomerUpdate) SetContactName(v string) *CustomerUpdate {
	_u.mutation.SetContactName(v)
	return _u
}

// SetNillableContactName sets the "contact_name" field if the given value is not nil.
func (_u *CustomerUpdate) SetNillableContactName(v *string) *CustomerUpdate {
	if v != nil {
		_u.SetContactName(*v)
	}
	return _u
}

// ClearContactName clears the value of the "contact_name" field.
func (_u *CustomerUpdate) ClearContactName() *CustomerUpdate {
	_u.mutation.ClearContactName()
	return _u
}

// SetContactEmail sets the "contact_email" field.
func (_u *CustomerUpdate) SetContactEmail(v string) *CustomerUpdate {
	_u.mutation.SetContactEmail(v)
	return _u
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_u *CustomerUpdate) SetNillableContactEmail(v *string) *CustomerUpdate {
	if v != nil {
		_u.SetContactEmail(*v)
	}
	return _u
}

// ClearContactEmail clears the value of the "contact_email" field.
func (_u *CustomerUpdate) ClearContactEmail() *CustomerUpdate {
	_u.mutation.ClearContactEmail()
	return _u
}

// SetContactPhone sets the "contact_phone" field.
func (_u *CustomerUpdate) SetContactPhone(v string) *CustomerUpdate {
	_u.mutation.SetContactPhone(v)
	return _u
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_u *CustomerUpdate) SetNillableContactPhone(v *string) *CustomerUpdate {
	if v != nil {
		_u.SetContactPhone(*v)
	}
	return _u
}

// ClearContactPhone clears the value of the "contact_phone" field.
func (_u *CustomerUpdate) ClearContactPhone() *CustomerUpdate {
	_u.mutation.ClearContactPhone()
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *CustomerUpdate) SetOrganization(v *Organization) *CustomerUpdate {
	return _u.SetOrganizationID(v.ID)
}

// AddProjectIDs adds the "projects" edge to the Project entity by IDs.
func (_u *CustomerUpdate) AddProjectIDs(ids ...uuid.UUID) *CustomerUpdate {
	_u.mutation.AddProjectIDs(ids...)
	return _u
}

// AddProjects adds the "projects" edges to the Project entity.
func (_u *CustomerUpdate) AddProjects(v ...*Project) *CustomerUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProjectIDs(ids...)
}

// Mutation returns the CustomerMutation object of the builder.
func (_u *CustomerUpdate) Mutation() *CustomerMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *CustomerUpdate) ClearOrganization() *CustomerUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearProjects clears all "projects" edges to the Project entity.
func (_u *CustomerUpdate) ClearProjects() *CustomerUpdate {
	_u.mutation.ClearProjects()
	return _u
}

// RemoveProjectIDs removes the "projects" edge to Project entities by IDs.
func (_u *CustomerUpdate) RemoveProjectIDs(ids ...uuid.UUID) *CustomerUpdate {
	_u.mutation.RemoveProjectIDs(ids...)
	return _u
}

// RemoveProjects removes "projects" edges to Project entities.
func (_u *CustomerUpdate) RemoveProjects(v ...*Project) *CustomerUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProjectIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CustomerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CustomerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomerUpdate) check() error {
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Customer.organization"`)
	}
	return nil
}

func (_u *CustomerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(customer.Table, customer.Columns, sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(customer.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Document(); ok {
		_spec.SetField(customer.FieldDocument, field.TypeString, value)
	}
	if _u.mutation.DocumentCleared() {
		_spec.ClearField(customer.FieldDocument, field.TypeString)
	}
	if value, ok := _u.mutation.ContactName(); ok {
		_spec.SetField(customer.FieldContactName, field.TypeString, value)
	}
	if _u.mutation.ContactNameCleared() {
		_spec.ClearField(customer.FieldContactName, field.TypeString)
	}
	if value, ok := _u.mutation.ContactEmail(); ok {
		_spec.SetField(customer.FieldContactEmail, field.TypeString, value)
	}
	if _u.mutation.ContactEmailCleared() {
		_spec.ClearField(customer.FieldContactEmail, field.TypeString)
	}
	if value, ok := _u.mutation.ContactPhone(); ok {
		_spec.SetField(customer.FieldContactPhone, field.TypeString, value)
	}
	if _u.mutation.ContactPhoneCleared() {
		_spec.ClearField(customer.FieldContactPhone, field.TypeString)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customer.OrganizationTable,
			Columns: []string{customer.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customer.OrganizationTable,
			Columns: []string{customer.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.ProjectsTable,
			Columns: []string{customer.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProjectsIDs(); len(nodes) > 0 && !_u.mutation.ProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.ProjectsTable,
			Columns: []string{customer.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.ProjectsTable,
			Columns: []string{customer.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CustomerUpdateOne is the builder for updating a single Customer entity.
type CustomerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CustomerMutation
}

// SetOrganizationID sets the "organization_id" field.
func (_u *CustomerUpdateOne) SetOrganizationID(v uuid.UUID) *CustomerUpdateOne {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *CustomerUpdateOne) SetNillableOrganizationID(v *uuid.UUID) *CustomerUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CustomerUpdateOne) SetName(v string) *CustomerUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CustomerUpdateOne) SetNillableName(v *string) *CustomerUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDocument sets the "document" field.
func (_u *CustomerUpdateOne) SetDocument(v string) *CustomerUpdateOne {
	_u.mutation.SetDocument(v)
	return _u
}

// SetNillableDocument sets the "document" field if the given value is not nil.
func (_u *CustomerUpdateOne) SetNillableDocument(v *string) *CustomerUpdateOne {
	if v != nil {
		_u.SetDocument(*v)
	}
	return _u
}

// ClearDocument clears the value of the "document" field.
func (_u *CustomerUpdateOne) ClearDocument() *CustomerUpdateOne {
	_u.mutation.ClearDocument()
	return _u
}

// SetContactName sets the "contact_name" field.
func (_u *CustomerUpdateOne) SetContactName(v string) *CustomerUpdateOne {
	_u.mutation.SetContactName(v)
	return _u
}

// SetNillableContactName sets the "contact_name" field if the given value is not nil.
func (_u *CustomerUpdateOne) SetNillableContactName(v *string) *CustomerUpdateOne {
	if v != nil {
		_u.SetContactName(*v)
	}
	return _u
}

// ClearContactName clears the value of the "contact_name" field.
func (_u *CustomerUpdateOne) ClearContactName() *CustomerUpdateOne {
	_u.mutation.ClearContactName()
	return _u
}

// SetContactEmail sets the "contact_email" field.
func (_u *CustomerUpdateOne) SetContactEmail(v string) *CustomerUpdateOne {
	_u.mutation.SetContactEmail(v)
	return _u
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_u *CustomerUpdateOne) SetNillableContactEmail(v *string) *CustomerUpdateOne {
	if v != nil {
		_u.SetContactEmail(*v)
	}
	return _u
}

// ClearContactEmail clears the value of the "contact_email" field.
func (_u *CustomerUpdateOne) ClearContactEmail() *CustomerUpdateOne {
	_u.mutation.ClearContactEmail()
	return _u
}

// SetContactPhone sets the "contact_phone" field.
func (_u *CustomerUpdateOne) SetContactPhone(v string) *CustomerUpdateOne {
	_u.mutation.SetContactPhone(v)
	return _u
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_u *CustomerUpdateOne) SetNillableContactPhone(v *string) *CustomerUpdateOne {
	if v != nil {
		_u.SetContactPhone(*v)
	}
	return _u
}

// ClearContactPhone clears the value of the "contact_phone" field.
func (_u *CustomerUpdateOne) ClearContactPhone() *CustomerUpdateOne {
	_u.mutation.ClearContactPhone()
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *CustomerUpdateOne) SetOrganization(v *Organization) *CustomerUpdateOne {
	return _u.SetOrganizationID(v.ID)
}

// AddProjectIDs adds the "projects" edge to the Project entity by IDs.
func (_u *CustomerUpdateOne) AddProjectIDs(ids ...uuid.UUID) *CustomerUpdateOne {
	_u.mutation.AddProjectIDs(ids...)
	return _u
}

// AddProjects adds the "projects" edges to the Project entity.
func (_u *CustomerUpdateOne) AddProjects(v ...*Project) *CustomerUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProjectIDs(ids...)
}

// Mutation returns the CustomerMutation object of the builder.
func (_u *CustomerUpdateOne) Mutation() *CustomerMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *CustomerUpdateOne) ClearOrganization() *CustomerUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearProjects clears all "projects" edges to the Project entity.
func (_u *CustomerUpdateOne) ClearProjects() *CustomerUpdateOne {
	_u.mutation.ClearProjects()
	return _u
}

// RemoveProjectIDs removes the "projects" edge to Project entities by IDs.
func (_u *CustomerUpdateOne) RemoveProjectIDs(ids ...uuid.UUID) *CustomerUpdateOne {
	_u.mutation.RemoveProjectIDs(ids...)
	return _u
}

// RemoveProjects removes "projects" edges to Project entities.
func (_u *CustomerUpdateOne) RemoveProjects(v ...*Project) *CustomerUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProjectIDs(ids...)
}

// Where appends a list predicates to the CustomerUpdate builder.
func (_u *CustomerUpdateOne) Where(ps ...predicate.Customer) *CustomerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CustomerUpdateOne) Select(field string, fields ...string) *CustomerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Customer entity.
func (_u *CustomerUpdateOne) Save(ctx context.Context) (*Customer, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomerUpdateOne) SaveX(ctx context.Context) *Customer {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CustomerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomerUpdateOne) check() error {
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Customer.organization"`)
	}
	return nil
}

func (_u *CustomerUpdateOne) sqlSave(ctx context.Context) (_node *Customer, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(customer.Table, customer.Columns, sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Customer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, customer.FieldID)
		for _, f := range fields {
			if !customer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != customer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(customer.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Document(); ok {
		_spec.SetField(customer.FieldDocument, field.TypeString, value)
	}
	if _u.mutation.DocumentCleared() {
		_spec.ClearField(customer.FieldDocument, field.TypeString)
	}
	if value, ok := _u.mutation.ContactName(); ok {
		_spec.SetField(customer.FieldContactName, field.TypeString, value)
	}
	if _u.mutation.ContactNameCleared() {
		_spec.ClearField(customer.FieldContactName, field.TypeString)
	}
	if value, ok := _u.mutation.ContactEmail(); ok {
		_spec.SetField(customer.FieldContactEmail, field.TypeString, value)
	}
	if _u.mutation.ContactEmailCleared() {
		_spec.ClearField(customer.FieldContactEmail, field.TypeString)
	}
	if value, ok := _u.mutation.ContactPhone(); ok {
		_spec.SetField(customer.FieldContactPhone, field.TypeString, value)
	}
	if _u.mutation.ContactPhoneCleared() {
		_spec.ClearField(customer.FieldContactPhone, field.TypeString)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customer.OrganizationTable,
			Columns: []string{customer.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customer.OrganizationTable,
			Columns: []string{customer.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.ProjectsTable,
			Columns: []string{customer.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProjectsIDs(); len(nodes) > 0 && !_u.mutation.ProjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.ProjectsTable,
			Columns: []string{customer.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customer.ProjectsTable,
			Columns: []string{customer.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Customer{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
