// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"working-time-tracker/ent/invite"
	"working-time-tracker/ent/organization"
	"working-time-tracker/ent/person"
	"working-time-tracker/ent/project"
	"working-time-tracker/ent/team"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Invite is the model entity for the Invite schema.
type Invite struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID uuid.UUID `json:"organization_id,omitempty"`
	// TokenHash holds the value of the "token_hash" field.
	TokenHash string `json:"-"`
	// Email holds the value of the "email" field.
	Email *string `json:"email,omitempty"`
	// Role holds the value of the "role" field.
	Role invite.Role `json:"role,omitempty"`
	// ClerkInvitationID holds the value of the "clerk_invitation_id" field.
	ClerkInvitationID *string `json:"clerk_invitation_id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID *uuid.UUID `json:"project_id,omitempty"`
	// PayRateCents holds the value of the "pay_rate_cents" field.
	PayRateCents *int `json:"pay_rate_cents,omitempty"`
	// TeamID holds the value of the "team_id" field.
	TeamID *uuid.UUID `json:"team_id,omitempty"`
	// Preset holds the value of the "preset" field.
	Preset *string `json:"preset,omitempty"`
	// CreatedByID holds the value of the "created_by_id" field.
	CreatedByID *uuid.UUID `json:"created_by_id,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// AcceptedAt holds the value of the "accepted_at" field.
	AcceptedAt *time.Time `json:"accepted_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InviteQuery when eager-loading is set.
	Edges        InviteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InviteEdges holds the relations/edges for other nodes in the graph.
type InviteEdges struct {
	// Organization holds the value of the organization edge.
	Organization *Organization `json:"organization,omitempty"`
	// CreatedBy holds the value of the created_by edge.
	CreatedBy *Person `json:"created_by,omitempty"`
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Team holds the value of the team edge.
	Team *Team `json:"team,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// OrganizationOrErr returns the Organization value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InviteEdges) OrganizationOrErr() (*Organization, error) {
	if e.Organization != nil {
		return e.Organization, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: organization.Label}
	}
	return nil, &NotLoadedError{edge: "organization"}
}

// CreatedByOrErr returns the CreatedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InviteEdges) CreatedByOrErr() (*Person, error) {
	if e.CreatedBy != nil {
		return e.CreatedBy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: person.Label}
	}
	return nil, &NotLoadedError{edge: "created_by"}
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InviteEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// TeamOrErr returns the Team value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InviteEdges) TeamOrErr() (*Team, error) {
	if e.Team != nil {
		return e.Team, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: team.Label}
	}
	return nil, &NotLoadedError{edge: "team"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Invite) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invite.FieldProjectID, invite.FieldTeamID, invite.FieldCreatedByID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case invite.FieldPayRateCents:
			values[i] = new(sql.NullInt64)
		case invite.FieldTokenHash, invite.FieldEmail, invite.FieldRole, invite.FieldClerkInvitationID, invite.FieldPreset:
			values[i] = new(sql.NullString)
		case invite.FieldExpiresAt, invite.FieldAcceptedAt, invite.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case invite.FieldID, invite.FieldOrganizationID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Invite fields.
func (_m *Invite) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invite.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case invite.FieldOrganizationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value != nil {
				_m.OrganizationID = *value
			}
		case invite.FieldTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_hash", values[i])
			} else if value.Valid {
				_m.TokenHash = value.String
			}
		case invite.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = new(string)
				*_m.Email = value.String
			}
		case invite.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = invite.Role(value.String)
			}
		case invite.FieldClerkInvitationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field clerk_invitation_id", values[i])
			} else if value.Valid {
				_m.ClerkInvitationID = new(string)
				*_m.ClerkInvitationID = value.String
			}
		case invite.FieldProjectID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = new(uuid.UUID)
				*_m.ProjectID = *value.S.(*uuid.UUID)
			}
		case invite.FieldPayRateCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pay_rate_cents", values[i])
			} else if value.Valid {
				_m.PayRateCents = new(int)
				*_m.PayRateCents = int(value.Int64)
			}
		case invite.FieldTeamID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value.Valid {
				_m.TeamID = new(uuid.UUID)
				*_m.TeamID = *value.S.(*uuid.UUID)
			}
		case invite.FieldPreset:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field preset", values[i])
			} else if value.Valid {
				_m.Preset = new(string)
				*_m.Preset = value.String
			}
		case invite.FieldCreatedByID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field created_by_id", values[i])
			} else if value.Valid {
				_m.CreatedByID = new(uuid.UUID)
				*_m.CreatedByID = *value.S.(*uuid.UUID)
			}
		case invite.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case invite.FieldAcceptedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field accepted_at", values[i])
			} else if value.Valid {
				_m.AcceptedAt = new(time.Time)
				*_m.AcceptedAt = value.Time
			}
		case invite.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Invite.
// This includes values selected through modifiers, order, etc.
func (_m *Invite) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOrganization queries the "organization" edge of the Invite entity.
func (_m *Invite) QueryOrganization() *OrganizationQuery {
	return NewInviteClient(_m.config).QueryOrganization(_m)
}

// QueryCreatedBy queries the "created_by" edge of the Invite entity.
func (_m *Invite) QueryCreatedBy() *PersonQuery {
	return NewInviteClient(_m.config).QueryCreatedBy(_m)
}

// QueryProject queries the "project" edge of the Invite entity.
func (_m *Invite) QueryProject() *ProjectQuery {
	return NewInviteClient(_m.config).QueryProject(_m)
}

// QueryTeam queries the "team" edge of the Invite entity.
func (_m *Invite) QueryTeam() *TeamQuery {
	return NewInviteClient(_m.config).QueryTeam(_m)
}

// Update returns a builder for updating this Invite.
// Note that you need to call Invite.Unwrap() before calling this method if this Invite
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Invite) Update() *InviteUpdateOne {
	return NewInviteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Invite entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Invite) Unwrap() *Invite {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Invite is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Invite) String() string {
	var builder strings.Builder
	builder.WriteString("Invite(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("organization_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrganizationID))
	builder.WriteString(", ")
	builder.WriteString("token_hash=<sensitive>")
	builder.WriteString(", ")
	if v := _m.Email; v != nil {
		builder.WriteString("email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", _m.Role))
	builder.WriteString(", ")
	if v := _m.ClerkInvitationID; v != nil {
		builder.WriteString("clerk_invitation_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProjectID; v != nil {
		builder.WriteString("project_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PayRateCents; v != nil {
		builder.WriteString("pay_rate_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TeamID; v != nil {
		builder.WriteString("team_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Preset; v != nil {
		builder.WriteString("preset=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CreatedByID; v != nil {
		builder.WriteString("created_by_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.AcceptedAt; v != nil {
		builder.WriteString("accepted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Invites is a parsable slice of Invite.
type Invites []*Invite
