// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"working-time-tracker/ent/integration"
	"working-time-tracker/ent/issuesync"
	"working-time-tracker/ent/predicate"
	"working-time-tracker/ent/task"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// IssueSyncUpdate is the builder for updating IssueSync entities.
type IssueSyncUpdate struct {
	config
	hooks    []Hook
	mutation *IssueSyncMutation
}

// Where appends a list predicates to the IssueSyncUpdate builder.
func (_u *IssueSyncUpdate) Where(ps ...predicate.IssueSync) *IssueSyncUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIntegrationID sets the "integration_id" field.
func (_u *IssueSyncUpdate) SetIntegrationID(v uuid.UUID) *IssueSyncUpdate {
	_u.mutation.SetIntegrationID(v)
	return _u
}

// SetNillableIntegrationID sets the "integration_id" field if the given value is not nil.
func (_u *IssueSyncUpdate) SetNillableIntegrationID(v *uuid.UUID) *IssueSyncUpdate {
	if v != nil {
		_u.SetIntegrationID(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *IssueSyncUpdate) SetTaskID(v uuid.UUID) *IssueSyncUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *IssueSyncUpdate) SetNillableTaskID(v *uuid.UUID) *IssueSyncUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// ClearTaskID clears the value of the "task_id" field.
func (_u *IssueSyncUpdate) ClearTaskID() *IssueSyncUpdate {
	_u.mutation.ClearTaskID()
	return _u
}

// SetItemID sets the "item_id" field.
func (_u *IssueSyncUpdate) SetItemID(v string) *IssueSyncUpdate {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *IssueSyncUpdate) SetNillableItemID(v *string) *IssueSyncUpdate {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *IssueSyncUpdate) SetState(v issuesync.State) *IssueSyncUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *IssueSyncUpdate) SetNillableState(v *issuesync.State) *IssueSyncUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *IssueSyncUpdate) SetTitle(v string) *IssueSyncUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *IssueSyncUpdate) SetNillableTitle(v *string) *IssueSyncUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *IssueSyncUpdate) SetBody(v string) *IssueSyncUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *IssueSyncUpdate) SetNillableBody(v *string) *IssueSyncUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *IssueSyncUpdate) SetLabels(v []string) *IssueSyncUpdate {
	_u.mutation.SetLabels(v)
	return _u
}

// AppendLabels appends value to the "labels" field.
func (_u *IssueSyncUpdate) AppendLabels(v []string) *IssueSyncUpdate {
	_u.mutation.AppendLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *IssueSyncUpdate) ClearLabels() *IssueSyncUpdate {
	_u.mutation.ClearLabels()
	return _u
}

// SetAssigneeLogins sets the "assignee_logins" field.
func (_u *IssueSyncUpdate) SetAssigneeLogins(v []string) *IssueSyncUpdate {
	_u.mutation.SetAssigneeLogins(v)
	return _u
}

// AppendAssigneeLogins appends value to the "assignee_logins" field.
func (_u *IssueSyncUpdate) AppendAssigneeLogins(v []string) *IssueSyncUpdate {
	_u.mutation.AppendAssigneeLogins(v)
	return _u
}

// ClearAssigneeLogins clears the value of the "assignee_logins" field.
func (_u *IssueSyncUpdate) ClearAssigneeLogins() *IssueSyncUpdate {
	_u.mutation.ClearAssigneeLogins()
	return _u
}

// SetMappedLogin sets the "mapped_login" field.
func (_u *IssueSyncUpdate) SetMappedLogin(v string) *IssueSyncUpdate {
	_u.mutation.SetMappedLogin(v)
	return _u
}

// SetNillableMappedLogin sets the "mapped_login" field if the given value is not nil.
func (_u *IssueSyncUpdate) SetNillableMappedLogin(v *string) *IssueSyncUpdate {
	if v != nil {
		_u.SetMappedLogin(*v)
	}
	return _u
}

// SetMappedPersonID sets the "mapped_person_id" field.
func (_u *IssueSyncUpdate) SetMappedPersonID(v uuid.UUID) *IssueSyncUpdate {
	_u.mutation.SetMappedPersonID(v)
	return _u
}

// SetNillableMappedPersonID sets the "mapped_person_id" field if the given value is not nil.
func (_u *IssueSyncUpdate) SetNillableMappedPersonID(v *uuid.UUID) *IssueSyncUpdate {
	if v != nil {
		_u.SetMappedPersonID(*v)
	}
	return _u
}

// ClearMappedPersonID clears the value of the "mapped_person_id" field.
func (_u *IssueSyncUpdate) ClearMappedPersonID() *IssueSyncUpdate {
	_u.mutation.ClearMappedPersonID()
	return _u
}

// SetDeadline sets the "deadline" field.
func (_u *IssueSyncUpdate) SetDeadline(v time.Time) *IssueSyncUpdate {
	_u.mutation.SetDeadline(v)
	return _u
}

// SetNillableDeadline sets the "deadline" field if the given value is not nil.
func (_u *IssueSyncUpdate) SetNillableDeadline(v *time.Time) *IssueSyncUpdate {
	if v != nil {
		_u.SetDeadline(*v)
	}
	return _u
}

// ClearDeadline clears the value of the "deadline" field.
func (_u *IssueSyncUpdate) ClearDeadline() *IssueSyncUpdate {
	_u.mutation.ClearDeadline()
	return _u
}

// SetStuckSig sets the "stuck_sig" field.
func (_u *IssueSyncUpdate) SetStuckSig(v string) *IssueSyncUpdate {
	_u.mutation.SetStuckSig(v)
	return _u
}

// SetNillableStuckSig sets the "stuck_sig" field if the given value is not nil.
func (_u *IssueSyncUpdate) SetNillableStuckSig(v *string) *IssueSyncUpdate {
	if v != nil {
		_u.SetStuckSig(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *IssueSyncUpdate) SetLastError(v string) *IssueSyncUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *IssueSyncUpdate) SetNillableLastError(v *string) *IssueSyncUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *IssueSyncUpdate) SetSyncedAt(v time.Time) *IssueSyncUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *IssueSyncUpdate) SetNillableSyncedAt(v *time.Time) *IssueSyncUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// SetIntegration sets the "integration" edge to the Integration entity.
func (_u *IssueSyncUpdate) SetIntegration(v *Integration) *IssueSyncUpdate {
	return _u.SetIntegrationID(v.ID)
}

// SetTask sets the "task" edge to the Task entity.
func (_u *IssueSyncUpdate) SetTask(v *Task) *IssueSyncUpdate {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the IssueSyncMutation object of the builder.
func (_u *IssueSyncUpdate) Mutation() *IssueSyncMutation {
	return _u.mutation
}

// ClearIntegration clears the "integration" edge to the Integration entity.
func (_u *IssueSyncUpdate) ClearIntegration() *IssueSyncUpdate {
	_u.mutation.ClearIntegration()
	return _u
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *IssueSyncUpdate) ClearTask() *IssueSyncUpdate {
	_u.mutation.ClearTask()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IssueSyncUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IssueSyncUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IssueSyncUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IssueSyncUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IssueSyncUpdate) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := issuesync.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "IssueSync.state": %w`, err)}
		}
	}
	if _u.mutation.IntegrationCleared() && len(_u.mutation.IntegrationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IssueSync.integration"`)
	}
	return nil
}

func (_u *IssueSyncUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(issuesync.Table, issuesync.Columns, sqlgraph.NewFieldSpec(issuesync.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ItemID(); ok {
		_spec.SetField(issuesync.FieldItemID, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(issuesync.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(issuesync.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(issuesync.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(issuesync.FieldLabels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLabels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, issuesync.FieldLabels, value)
		})
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(issuesync.FieldLabels, field.TypeJSON)
	}
	if value, ok := _u.mutation.AssigneeLogins(); ok {
		_spec.SetField(issuesync.FieldAssigneeLogins, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAssigneeLogins(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, issuesync.FieldAssigneeLogins, value)
		})
	}
	if _u.mutation.AssigneeLoginsCleared() {
		_spec.ClearField(issuesync.FieldAssigneeLogins, field.TypeJSON)
	}
	if value, ok := _u.mutation.MappedLogin(); ok {
		_spec.SetField(issuesync.FieldMappedLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.MappedPersonID(); ok {
		_spec.SetField(issuesync.FieldMappedPersonID, field.TypeUUID, value)
	}
	if _u.mutation.MappedPersonIDCleared() {
		_spec.ClearField(issuesync.FieldMappedPersonID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Deadline(); ok {
		_spec.SetField(issuesync.FieldDeadline, field.TypeTime, value)
	}
	if _u.mutation.DeadlineCleared() {
		_spec.ClearField(issuesync.FieldDeadline, field.TypeTime)
	}
	if value, ok := _u.mutation.StuckSig(); ok {
		_spec.SetField(issuesync.FieldStuckSig, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(issuesync.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(issuesync.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.IntegrationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issuesync.IntegrationTable,
			Columns: []string{issuesync.IntegrationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IntegrationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issuesync.IntegrationTable,
			Columns: []string{issuesync.IntegrationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   issuesync.TaskTable,
			Columns: []string{issuesync.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   issuesync.TaskTable,
			Columns: []string{issuesync.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{issuesync.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IssueSyncUpdateOne is the builder for updating a single IssueSync entity.
type IssueSyncUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IssueSyncMutation
}

// SetIntegrationID sets the "integration_id" field.
func (_u *IssueSyncUpdateOne) SetIntegrationID(v uuid.UUID) *IssueSyncUpdateOne {
	_u.mutation.SetIntegrationID(v)
	return _u
}

// SetNillableIntegrationID sets the "integration_id" field if the given value is not nil.
func (_u *IssueSyncUpdateOne) SetNillableIntegrationID(v *uuid.UUID) *IssueSyncUpdateOne {
	if v != nil {
		_u.SetIntegrationID(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *IssueSyncUpdateOne) SetTaskID(v uuid.UUID) *IssueSyncUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *IssueSyncUpdateOne) SetNillableTaskID(v *uuid.UUID) *IssueSyncUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// ClearTaskID clears the value of the "task_id" field.
func (_u *IssueSyncUpdateOne) ClearTaskID() *IssueSyncUpdateOne {
	_u.mutation.ClearTaskID()
	return _u
}

// SetItemID sets the "item_id" field.
func (_u *IssueSyncUpdateOne) SetItemID(v string) *IssueSyncUpdateOne {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *IssueSyncUpdateOne) SetNillableItemID(v *string) *IssueSyncUpdateOne {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetState sets the "state" field.
func (_u *IssueSyncUpdateOne) SetState(v issuesync.State) *IssueSyncUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *IssueSyncUpdateOne) SetNillableState(v *issuesync.State) *IssueSyncUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *IssueSyncUpdateOne) SetTitle(v string) *IssueSyncUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *IssueSyncUpdateOne) SetNillableTitle(v *string) *IssueSyncUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *IssueSyncUpdateOne) SetBody(v string) *IssueSyncUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *IssueSyncUpdateOne) SetNillableBody(v *string) *IssueSyncUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetLabels sets the "labels" field.
func (_u *IssueSyncUpdateOne) SetLabels(v []string) *IssueSyncUpdateOne {
	_u.mutation.SetLabels(v)
	return _u
}

// AppendLabels appends value to the "labels" field.
func (_u *IssueSyncUpdateOne) AppendLabels(v []string) *IssueSyncUpdateOne {
	_u.mutation.AppendLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *IssueSyncUpdateOne) ClearLabels() *IssueSyncUpdateOne {
	_u.mutation.ClearLabels()
	return _u
}

// SetAssigneeLogins sets the "assignee_logins" field.
func (_u *IssueSyncUpdateOne) SetAssigneeLogins(v []string) *IssueSyncUpdateOne {
	_u.mutation.SetAssigneeLogins(v)
	return _u
}

// AppendAssigneeLogins appends value to the "assignee_logins" field.
func (_u *IssueSyncUpdateOne) AppendAssigneeLogins(v []string) *IssueSyncUpdateOne {
	_u.mutation.AppendAssigneeLogins(v)
	return _u
}

// ClearAssigneeLogins clears the value of the "assignee_logins" field.
func (_u *IssueSyncUpdateOne) ClearAssigneeLogins() *IssueSyncUpdateOne {
	_u.mutation.ClearAssigneeLogins()
	return _u
}

// SetMappedLogin sets the "mapped_login" field.
func (_u *IssueSyncUpdateOne) SetMappedLogin(v string) *IssueSyncUpdateOne {
	_u.mutation.SetMappedLogin(v)
	return _u
}

// SetNillableMappedLogin sets the "mapped_login" field if the given value is not nil.
func (_u *IssueSyncUpdateOne) SetNillableMappedLogin(v *string) *IssueSyncUpdateOne {
	if v != nil {
		_u.SetMappedLogin(*v)
	}
	return _u
}

// SetMappedPersonID sets the "mapped_person_id" field.
func (_u *IssueSyncUpdateOne) SetMappedPersonID(v uuid.UUID) *IssueSyncUpdateOne {
	_u.mutation.SetMappedPersonID(v)
	return _u
}

// SetNillableMappedPersonID sets the "mapped_person_id" field if the given value is not nil.
func (_u *IssueSyncUpdateOne) SetNillableMappedPersonID(v *uuid.UUID) *IssueSyncUpdateOne {
	if v != nil {
		_u.SetMappedPersonID(*v)
	}
	return _u
}

// ClearMappedPersonID clears the value of the "mapped_person_id" field.
func (_u *IssueSyncUpdateOne) ClearMappedPersonID() *IssueSyncUpdateOne {
	_u.mutation.ClearMappedPersonID()
	return _u
}

// SetDeadline sets the "deadline" field.
func (_u *IssueSyncUpdateOne) SetDeadline(v time.Time) *IssueSyncUpdateOne {
	_u.mutation.SetDeadline(v)
	return _u
}

// SetNillableDeadline sets the "deadline" field if the given value is not nil.
func (_u *IssueSyncUpdateOne) SetNillableDeadline(v *time.Time) *IssueSyncUpdateOne {
	if v != nil {
		_u.SetDeadline(*v)
	}
	return _u
}

// ClearDeadline clears the value of the "deadline" field.
func (_u *IssueSyncUpdateOne) ClearDeadline() *IssueSyncUpdateOne {
	_u.mutation.ClearDeadline()
	return _u
}

// SetStuckSig sets the "stuck_sig" field.
func (_u *IssueSyncUpdateOne) SetStuckSig(v string) *IssueSyncUpdateOne {
	_u.mutation.SetStuckSig(v)
	return _u
}

// SetNillableStuckSig sets the "stuck_sig" field if the given value is not nil.
func (_u *IssueSyncUpdateOne) SetNillableStuckSig(v *string) *IssueSyncUpdateOne {
	if v != nil {
		_u.SetStuckSig(*v)
	}
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *IssueSyncUpdateOne) SetLastError(v string) *IssueSyncUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *IssueSyncUpdateOne) SetNillableLastError(v *string) *IssueSyncUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *IssueSyncUpdateOne) SetSyncedAt(v time.Time) *IssueSyncUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *IssueSyncUpdateOne) SetNillableSyncedAt(v *time.Time) *IssueSyncUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// SetIntegration sets the "integration" edge to the Integration entity.
func (_u *IssueSyncUpdateOne) SetIntegration(v *Integration) *IssueSyncUpdateOne {
	return _u.SetIntegrationID(v.ID)
}

// SetTask sets the "task" edge to the Task entity.
func (_u *IssueSyncUpdateOne) SetTask(v *Task) *IssueSyncUpdateOne {
	return _u.SetTaskID(v.ID)
}

// Mutation returns the IssueSyncMutation object of the builder.
func (_u *IssueSyncUpdateOne) Mutation() *IssueSyncMutation {
	return _u.mutation
}

// ClearIntegration clears the "integration" edge to the Integration entity.
func (_u *IssueSyncUpdateOne) ClearIntegration() *IssueSyncUpdateOne {
	_u.mutation.ClearIntegration()
	return _u
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *IssueSyncUpdateOne) ClearTask() *IssueSyncUpdateOne {
	_u.mutation.ClearTask()
	return _u
}

// Where appends a list predicates to the IssueSyncUpdate builder.
func (_u *IssueSyncUpdateOne) Where(ps ...predicate.IssueSync) *IssueSyncUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IssueSyncUpdateOne) Select(field string, fields ...string) *IssueSyncUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IssueSync entity.
func (_u *IssueSyncUpdateOne) Save(ctx context.Context) (*IssueSync, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IssueSyncUpdateOne) SaveX(ctx context.Context) *IssueSync {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IssueSyncUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IssueSyncUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IssueSyncUpdateOne) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := issuesync.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "IssueSync.state": %w`, err)}
		}
	}
	if _u.mutation.IntegrationCleared() && len(_u.mutation.IntegrationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "IssueSync.integration"`)
	}
	return nil
}

func (_u *IssueSyncUpdateOne) sqlSave(ctx context.Context) (_node *IssueSync, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(issuesync.Table, issuesync.Columns, sqlgraph.NewFieldSpec(issuesync.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IssueSync.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, issuesync.FieldID)
		for _, f := range fields {
			if !issuesync.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != issuesync.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ItemID(); ok {
		_spec.SetField(issuesync.FieldItemID, field.TypeString, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(issuesync.FieldState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(issuesync.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(issuesync.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(issuesync.FieldLabels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedLabels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, issuesync.FieldLabels, value)
		})
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(issuesync.FieldLabels, field.TypeJSON)
	}
	if value, ok := _u.mutation.AssigneeLogins(); ok {
		_spec.SetField(issuesync.FieldAssigneeLogins, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAssigneeLogins(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, issuesync.FieldAssigneeLogins, value)
		})
	}
	if _u.mutation.AssigneeLoginsCleared() {
		_spec.ClearField(issuesync.FieldAssigneeLogins, field.TypeJSON)
	}
	if value, ok := _u.mutation.MappedLogin(); ok {
		_spec.SetField(issuesync.FieldMappedLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.MappedPersonID(); ok {
		_spec.SetField(issuesync.FieldMappedPersonID, field.TypeUUID, value)
	}
	if _u.mutation.MappedPersonIDCleared() {
		_spec.ClearField(issuesync.FieldMappedPersonID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Deadline(); ok {
		_spec.SetField(issuesync.FieldDeadline, field.TypeTime, value)
	}
	if _u.mutation.DeadlineCleared() {
		_spec.ClearField(issuesync.FieldDeadline, field.TypeTime)
	}
	if value, ok := _u.mutation.StuckSig(); ok {
		_spec.SetField(issuesync.FieldStuckSig, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(issuesync.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(issuesync.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.IntegrationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issuesync.IntegrationTable,
			Columns: []string{issuesync.IntegrationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IntegrationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   issuesync.IntegrationTable,
			Columns: []string{issuesync.IntegrationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   issuesync.TaskTable,
			Columns: []string{issuesync.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   issuesync.TaskTable,
			Columns: []string{issuesync.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &IssueSync{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{issuesync.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
