// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"working-time-tracker/ent/customer"
	"working-time-tracker/ent/invite"
	"working-time-tracker/ent/organization"
	"working-time-tracker/ent/person"
	"working-time-tracker/ent/project"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OrganizationCreate is the builder for creating a Organization entity.
type OrganizationCreate struct {
	config
	mutation *OrganizationMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *OrganizationCreate) SetName(v string) *OrganizationCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *OrganizationCreate) SetSummary(v string) *OrganizationCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableSummary(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *OrganizationCreate) SetDescription(v string) *OrganizationCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableDescription(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetIndustry sets the "industry" field.
func (_c *OrganizationCreate) SetIndustry(v string) *OrganizationCreate {
	_c.mutation.SetIndustry(v)
	return _c
}

// SetNillableIndustry sets the "industry" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableIndustry(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetIndustry(*v)
	}
	return _c
}

// SetFoundedYear sets the "founded_year" field.
func (_c *OrganizationCreate) SetFoundedYear(v int) *OrganizationCreate {
	_c.mutation.SetFoundedYear(v)
	return _c
}

// SetNillableFoundedYear sets the "founded_year" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableFoundedYear(v *int) *OrganizationCreate {
	if v != nil {
		_c.SetFoundedYear(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *OrganizationCreate) SetSize(v string) *OrganizationCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableSize(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetWebsite sets the "website" field.
func (_c *OrganizationCreate) SetWebsite(v string) *OrganizationCreate {
	_c.mutation.SetWebsite(v)
	return _c
}

// SetNillableWebsite sets the "website" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableWebsite(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetWebsite(*v)
	}
	return _c
}

// SetContactEmail sets the "contact_email" field.
func (_c *OrganizationCreate) SetContactEmail(v string) *OrganizationCreate {
	_c.mutation.SetContactEmail(v)
	return _c
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableContactEmail(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetContactEmail(*v)
	}
	return _c
}

// SetPhone sets the "phone" field.
func (_c *OrganizationCreate) SetPhone(v string) *OrganizationCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillablePhone(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetLinkedinURL sets the "linkedin_url" field.
func (_c *OrganizationCreate) SetLinkedinURL(v string) *OrganizationCreate {
	_c.mutation.SetLinkedinURL(v)
	return _c
}

// SetNillableLinkedinURL sets the "linkedin_url" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableLinkedinURL(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetLinkedinURL(*v)
	}
	return _c
}

// SetInstagramURL sets the "instagram_url" field.
func (_c *OrganizationCreate) SetInstagramURL(v string) *OrganizationCreate {
	_c.mutation.SetInstagramURL(v)
	return _c
}

// SetNillableInstagramURL sets the "instagram_url" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableInstagramURL(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetInstagramURL(*v)
	}
	return _c
}

// SetLegalName sets the "legal_name" field.
func (_c *OrganizationCreate) SetLegalName(v string) *OrganizationCreate {
	_c.mutation.SetLegalName(v)
	return _c
}

// SetNillableLegalName sets the "legal_name" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableLegalName(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetLegalName(*v)
	}
	return _c
}

// SetCnpj sets the "cnpj" field.
func (_c *OrganizationCreate) SetCnpj(v string) *OrganizationCreate {
	_c.mutation.SetCnpj(v)
	return _c
}

// SetNillableCnpj sets the "cnpj" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableCnpj(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetCnpj(*v)
	}
	return _c
}

// SetAddressLine1 sets the "address_line1" field.
func (_c *OrganizationCreate) SetAddressLine1(v string) *OrganizationCreate {
	_c.mutation.SetAddressLine1(v)
	return _c
}

// SetNillableAddressLine1 sets the "address_line1" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableAddressLine1(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetAddressLine1(*v)
	}
	return _c
}

// SetAddressLine2 sets the "address_line2" field.
func (_c *OrganizationCreate) SetAddressLine2(v string) *OrganizationCreate {
	_c.mutation.SetAddressLine2(v)
	return _c
}

// SetNillableAddressLine2 sets the "address_line2" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableAddressLine2(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetAddressLine2(*v)
	}
	return _c
}

// SetCity sets the "city" field.
func (_c *OrganizationCreate) SetCity(v string) *OrganizationCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableCity(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetCity(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *OrganizationCreate) SetState(v string) *OrganizationCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableState(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetPostalCode sets the "postal_code" field.
func (_c *OrganizationCreate) SetPostalCode(v string) *OrganizationCreate {
	_c.mutation.SetPostalCode(v)
	return _c
}

// SetNillablePostalCode sets the "postal_code" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillablePostalCode(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetPostalCode(*v)
	}
	return _c
}

// SetCountry sets the "country" field.
func (_c *OrganizationCreate) SetCountry(v string) *OrganizationCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableCountry(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetCountry(*v)
	}
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *OrganizationCreate) SetTimezone(v string) *OrganizationCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableTimezone(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetTimezone(*v)
	}
	return _c
}

// SetWeeklyHours sets the "weekly_hours" field.
func (_c *OrganizationCreate) SetWeeklyHours(v int) *OrganizationCreate {
	_c.mutation.SetWeeklyHours(v)
	return _c
}

// SetNillableWeeklyHours sets the "weekly_hours" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableWeeklyHours(v *int) *OrganizationCreate {
	if v != nil {
		_c.SetWeeklyHours(*v)
	}
	return _c
}

// SetDefaultSprintDays sets the "default_sprint_days" field.
func (_c *OrganizationCreate) SetDefaultSprintDays(v int) *OrganizationCreate {
	_c.mutation.SetDefaultSprintDays(v)
	return _c
}

// SetNillableDefaultSprintDays sets the "default_sprint_days" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableDefaultSprintDays(v *int) *OrganizationCreate {
	if v != nil {
		_c.SetDefaultSprintDays(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *OrganizationCreate) SetCurrency(v string) *OrganizationCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableCurrency(v *string) *OrganizationCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrganizationCreate) SetCreatedAt(v time.Time) *OrganizationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableCreatedAt(v *time.Time) *OrganizationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OrganizationCreate) SetID(v uuid.UUID) *OrganizationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OrganizationCreate) SetNillableID(v *uuid.UUID) *OrganizationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddPersonIDs adds the "persons" edge to the Person entity by IDs.
func (_c *OrganizationCreate) AddPersonIDs(ids ...uuid.UUID) *OrganizationCreate {
	_c.mutation.AddPersonIDs(ids...)
	return _c
}

// AddPersons adds the "persons" edges to the Person entity.
func (_c *OrganizationCreate) AddPersons(v ...*Person) *OrganizationCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPersonIDs(ids...)
}

// AddProjectIDs adds the "projects" edge to the Project entity by IDs.
func (_c *OrganizationCreate) AddProjectIDs(ids ...uuid.UUID) *OrganizationCreate {
	_c.mutation.AddProjectIDs(ids...)
	return _c
}

// AddProjects adds the "projects" edges to the Project entity.
func (_c *OrganizationCreate) AddProjects(v ...*Project) *OrganizationCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProjectIDs(ids...)
}

// AddCustomerIDs adds the "customers" edge to the Customer entity by IDs.
func (_c *OrganizationCreate) AddCustomerIDs(ids ...uuid.UUID) *OrganizationCreate {
	_c.mutation.AddCustomerIDs(ids...)
	return _c
}

// AddCustomers adds the "customers" edges to the Customer entity.
func (_c *OrganizationCreate) AddCustomers(v ...*Customer) *OrganizationCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCustomerIDs(ids...)
}

// AddInviteIDs adds the "invites" edge to the Invite entity by IDs.
func (_c *OrganizationCreate) AddInviteIDs(ids ...uuid.UUID) *OrganizationCreate {
	_c.mutation.AddInviteIDs(ids...)
	return _c
}

// AddInvites adds the "invites" edges to the Invite entity.
func (_c *OrganizationCreate) AddInvites(v ...*Invite) *OrganizationCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInviteIDs(ids...)
}

// Mutation returns the OrganizationMutation object of the builder.
func (_c *OrganizationCreate) Mutation() *OrganizationMutation {
	return _c.mutation
}

// Save creates the Organization in the database.
func (_c *OrganizationCreate) Save(ctx context.Context) (*Organization, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrganizationCreate) SaveX(ctx context.Context) *Organization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrganizationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrganizationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrganizationCreate) defaults() {
	if _, ok := _c.mutation.Timezone(); !ok {
		v := organization.DefaultTimezone
		_c.mutation.SetTimezone(v)
	}
	if _, ok := _c.mutation.DefaultSprintDays(); !ok {
		v := organization.DefaultDefaultSprintDays
		_c.mutation.SetDefaultSprintDays(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := organization.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := organization.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := organization.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrganizationCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Organization.name"`)}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "Organization.timezone"`)}
	}
	if _, ok := _c.mutation.DefaultSprintDays(); !ok {
		return &ValidationError{Name: "default_sprint_days", err: errors.New(`ent: missing required field "Organization.default_sprint_days"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Organization.currency"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Organization.created_at"`)}
	}
	return nil
}

func (_c *OrganizationCreate) sqlSave(ctx context.Context) (*Organization, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrganizationCreate) createSpec() (*Organization, *sqlgraph.CreateSpec) {
	var (
		_node = &Organization{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(organization.Table, sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(organization.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(organization.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(organization.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Industry(); ok {
		_spec.SetField(organization.FieldIndustry, field.TypeString, value)
		_node.Industry = value
	}
	if value, ok := _c.mutation.FoundedYear(); ok {
		_spec.SetField(organization.FieldFoundedYear, field.TypeInt, value)
		_node.FoundedYear = &value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(organization.FieldSize, field.TypeString, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Website(); ok {
		_spec.SetField(organization.FieldWebsite, field.TypeString, value)
		_node.Website = value
	}
	if value, ok := _c.mutation.ContactEmail(); ok {
		_spec.SetField(organization.FieldContactEmail, field.TypeString, value)
		_node.ContactEmail = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(organization.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.LinkedinURL(); ok {
		_spec.SetField(organization.FieldLinkedinURL, field.TypeString, value)
		_node.LinkedinURL = value
	}
	if value, ok := _c.mutation.InstagramURL(); ok {
		_spec.SetField(organization.FieldInstagramURL, field.TypeString, value)
		_node.InstagramURL = value
	}
	if value, ok := _c.mutation.LegalName(); ok {
		_spec.SetField(organization.FieldLegalName, field.TypeString, value)
		_node.LegalName = value
	}
	if value, ok := _c.mutation.Cnpj(); ok {
		_spec.SetField(organization.FieldCnpj, field.TypeString, value)
		_node.Cnpj = value
	}
	if value, ok := _c.mutation.AddressLine1(); ok {
		_spec.SetField(organization.FieldAddressLine1, field.TypeString, value)
		_node.AddressLine1 = value
	}
	if value, ok := _c.mutation.AddressLine2(); ok {
		_spec.SetField(organization.FieldAddressLine2, field.TypeString, value)
		_node.AddressLine2 = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(organization.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(organization.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.PostalCode(); ok {
		_spec.SetField(organization.FieldPostalCode, field.TypeString, value)
		_node.PostalCode = value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(organization.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(organization.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.WeeklyHours(); ok {
		_spec.SetField(organization.FieldWeeklyHours, field.TypeInt, value)
		_node.WeeklyHours = &value
	}
	if value, ok := _c.mutation.DefaultSprintDays(); ok {
		_spec.SetField(organization.FieldDefaultSprintDays, field.TypeInt, value)
		_node.DefaultSprintDays = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(organization.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(organization.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PersonsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.PersonsTable,
			Columns: []string{organization.PersonsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.ProjectsTable,
			Columns: []string{organization.ProjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CustomersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.CustomersTable,
			Columns: []string{organization.CustomersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InvitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.InvitesTable,
			Columns: []string{organization.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrganizationCreateBulk is the builder for creating many Organization entities in bulk.
type OrganizationCreateBulk struct {
	config
	err      error
	builders []*OrganizationCreate
}

// Save creates the Organization entities in the database.
func (_c *OrganizationCreateBulk) Save(ctx context.Context) ([]*Organization, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Organization, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrganizationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrganizationCreateBulk) SaveX(ctx context.Context) []*Organization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrganizationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrganizationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
