// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"working-time-tracker/ent/allocation"
	"working-time-tracker/ent/customer"
	"working-time-tracker/ent/integration"
	"working-time-tracker/ent/invite"
	"working-time-tracker/ent/label"
	"working-time-tracker/ent/organization"
	"working-time-tracker/ent/predicate"
	"working-time-tracker/ent/project"
	"working-time-tracker/ent/task"
	"working-time-tracker/ent/team"
	"working-time-tracker/ent/worksession"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProjectUpdate is the builder for updating Project entities.
type ProjectUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdate) Where(ps ...predicate.Project) *ProjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *ProjectUpdate) SetOrganizationID(v uuid.UUID) *ProjectUpdate {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableOrganizationID(v *uuid.UUID) *ProjectUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProjectUpdate) SetName(v string) *ProjectUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableName(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProjectUpdate) SetDescription(v string) *ProjectUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableDescription(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProjectUpdate) ClearDescription() *ProjectUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetGithubRepoURL sets the "github_repo_url" field.
func (_u *ProjectUpdate) SetGithubRepoURL(v string) *ProjectUpdate {
	_u.mutation.SetGithubRepoURL(v)
	return _u
}

// SetNillableGithubRepoURL sets the "github_repo_url" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableGithubRepoURL(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetGithubRepoURL(*v)
	}
	return _u
}

// ClearGithubRepoURL clears the value of the "github_repo_url" field.
func (_u *ProjectUpdate) ClearGithubRepoURL() *ProjectUpdate {
	_u.mutation.ClearGithubRepoURL()
	return _u
}

// SetGitlabRepoURL sets the "gitlab_repo_url" field.
func (_u *ProjectUpdate) SetGitlabRepoURL(v string) *ProjectUpdate {
	_u.mutation.SetGitlabRepoURL(v)
	return _u
}

// SetNillableGitlabRepoURL sets the "gitlab_repo_url" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableGitlabRepoURL(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetGitlabRepoURL(*v)
	}
	return _u
}

// ClearGitlabRepoURL clears the value of the "gitlab_repo_url" field.
func (_u *ProjectUpdate) ClearGitlabRepoURL() *ProjectUpdate {
	_u.mutation.ClearGitlabRepoURL()
	return _u
}

// SetSprintDurationDays sets the "sprint_duration_days" field.
func (_u *ProjectUpdate) SetSprintDurationDays(v int) *ProjectUpdate {
	_u.mutation.ResetSprintDurationDays()
	_u.mutation.SetSprintDurationDays(v)
	return _u
}

// SetNillableSprintDurationDays sets the "sprint_duration_days" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableSprintDurationDays(v *int) *ProjectUpdate {
	if v != nil {
		_u.SetSprintDurationDays(*v)
	}
	return _u
}

// AddSprintDurationDays adds value to the "sprint_duration_days" field.
func (_u *ProjectUpdate) AddSprintDurationDays(v int) *ProjectUpdate {
	_u.mutation.AddSprintDurationDays(v)
	return _u
}

// SetDailyTime sets the "daily_time" field.
func (_u *ProjectUpdate) SetDailyTime(v string) *ProjectUpdate {
	_u.mutation.SetDailyTime(v)
	return _u
}

// SetNillableDailyTime sets the "daily_time" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableDailyTime(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetDailyTime(*v)
	}
	return _u
}

// ClearDailyTime clears the value of the "daily_time" field.
func (_u *ProjectUpdate) ClearDailyTime() *ProjectUpdate {
	_u.mutation.ClearDailyTime()
	return _u
}

// SetWeeklySyncDay sets the "weekly_sync_day" field.
func (_u *ProjectUpdate) SetWeeklySyncDay(v string) *ProjectUpdate {
	_u.mutation.SetWeeklySyncDay(v)
	return _u
}

// SetNillableWeeklySyncDay sets the "weekly_sync_day" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableWeeklySyncDay(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetWeeklySyncDay(*v)
	}
	return _u
}

// ClearWeeklySyncDay clears the value of the "weekly_sync_day" field.
func (_u *ProjectUpdate) ClearWeeklySyncDay() *ProjectUpdate {
	_u.mutation.ClearWeeklySyncDay()
	return _u
}

// SetWeeklySyncTime sets the "weekly_sync_time" field.
func (_u *ProjectUpdate) SetWeeklySyncTime(v string) *ProjectUpdate {
	_u.mutation.SetWeeklySyncTime(v)
	return _u
}

// SetNillableWeeklySyncTime sets the "weekly_sync_time" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableWeeklySyncTime(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetWeeklySyncTime(*v)
	}
	return _u
}

// ClearWeeklySyncTime clears the value of the "weekly_sync_time" field.
func (_u *ProjectUpdate) ClearWeeklySyncTime() *ProjectUpdate {
	_u.mutation.ClearWeeklySyncTime()
	return _u
}

// SetCustomerMeetingDay sets the "customer_meeting_day" field.
func (_u *ProjectUpdate) SetCustomerMeetingDay(v string) *ProjectUpdate {
	_u.mutation.SetCustomerMeetingDay(v)
	return _u
}

// SetNillableCustomerMeetingDay sets the "customer_meeting_day" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableCustomerMeetingDay(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetCustomerMeetingDay(*v)
	}
	return _u
}

// ClearCustomerMeetingDay clears the value of the "customer_meeting_day" field.
func (_u *ProjectUpdate) ClearCustomerMeetingDay() *ProjectUpdate {
	_u.mutation.ClearCustomerMeetingDay()
	return _u
}

// SetCustomerMeetingTime sets the "customer_meeting_time" field.
func (_u *ProjectUpdate) SetCustomerMeetingTime(v string) *ProjectUpdate {
	_u.mutation.SetCustomerMeetingTime(v)
	return _u
}

// SetNillableCustomerMeetingTime sets the "customer_meeting_time" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableCustomerMeetingTime(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetCustomerMeetingTime(*v)
	}
	return _u
}

// ClearCustomerMeetingTime clears the value of the "customer_meeting_time" field.
func (_u *ProjectUpdate) ClearCustomerMeetingTime() *ProjectUpdate {
	_u.mutation.ClearCustomerMeetingTime()
	return _u
}

// SetCustomerID sets the "customer_id" field.
func (_u *ProjectUpdate) SetCustomerID(v uuid.UUID) *ProjectUpdate {
	_u.mutation.SetCustomerID(v)
	return _u
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableCustomerID(v *uuid.UUID) *ProjectUpdate {
	if v != nil {
		_u.SetCustomerID(*v)
	}
	return _u
}

// ClearCustomerID clears the value of the "customer_id" field.
func (_u *ProjectUpdate) ClearCustomerID() *ProjectUpdate {
	_u.mutation.ClearCustomerID()
	return _u
}

// SetBillRateCents sets the "bill_rate_cents" field.
func (_u *ProjectUpdate) SetBillRateCents(v int) *ProjectUpdate {
	_u.mutation.ResetBillRateCents()
	_u.mutation.SetBillRateCents(v)
	return _u
}

// SetNillableBillRateCents sets the "bill_rate_cents" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableBillRateCents(v *int) *ProjectUpdate {
	if v != nil {
		_u.SetBillRateCents(*v)
	}
	return _u
}

// AddBillRateCents adds value to the "bill_rate_cents" field.
func (_u *ProjectUpdate) AddBillRateCents(v int) *ProjectUpdate {
	_u.mutation.AddBillRateCents(v)
	return _u
}

// ClearBillRateCents clears the value of the "bill_rate_cents" field.
func (_u *ProjectUpdate) ClearBillRateCents() *ProjectUpdate {
	_u.mutation.ClearBillRateCents()
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *ProjectUpdate) SetOrganization(v *Organization) *ProjectUpdate {
	return _u.SetOrganizationID(v.ID)
}

// SetCustomer sets the "customer" edge to the Customer entity.
func (_u *ProjectUpdate) SetCustomer(v *Customer) *ProjectUpdate {
	return _u.SetCustomerID(v.ID)
}

// AddTeamIDs adds the "teams" edge to the Team entity by IDs.
func (_u *ProjectUpdate) AddTeamIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddTeamIDs(ids...)
	return _u
}

// AddTeams adds the "teams" edges to the Team entity.
func (_u *ProjectUpdate) AddTeams(v ...*Team) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamIDs(ids...)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *ProjectUpdate) AddTaskIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *ProjectUpdate) AddTasks(v ...*Task) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// AddWorkSessionIDs adds the "work_sessions" edge to the WorkSession entity by IDs.
func (_u *ProjectUpdate) AddWorkSessionIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddWorkSessionIDs(ids...)
	return _u
}

// AddWorkSessions adds the "work_sessions" edges to the WorkSession entity.
func (_u *ProjectUpdate) AddWorkSessions(v ...*WorkSession) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWorkSessionIDs(ids...)
}

// AddIntegrationIDs adds the "integrations" edge to the Integration entity by IDs.
func (_u *ProjectUpdate) AddIntegrationIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddIntegrationIDs(ids...)
	return _u
}

// AddIntegrations adds the "integrations" edges to the Integration entity.
func (_u *ProjectUpdate) AddIntegrations(v ...*Integration) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIntegrationIDs(ids...)
}

// AddAllocationIDs adds the "allocations" edge to the Allocation entity by IDs.
func (_u *ProjectUpdate) AddAllocationIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddAllocationIDs(ids...)
	return _u
}

// AddAllocations adds the "allocations" edges to the Allocation entity.
func (_u *ProjectUpdate) AddAllocations(v ...*Allocation) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAllocationIDs(ids...)
}

// AddInviteIDs adds the "invites" edge to the Invite entity by IDs.
func (_u *ProjectUpdate) AddInviteIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddInviteIDs(ids...)
	return _u
}

// AddInvites adds the "invites" edges to the Invite entity.
func (_u *ProjectUpdate) AddInvites(v ...*Invite) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInviteIDs(ids...)
}

// AddLabelIDs adds the "labels" edge to the Label entity by IDs.
func (_u *ProjectUpdate) AddLabelIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.AddLabelIDs(ids...)
	return _u
}

// AddLabels adds the "labels" edges to the Label entity.
func (_u *ProjectUpdate) AddLabels(v ...*Label) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLabelIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdate) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *ProjectUpdate) ClearOrganization() *ProjectUpdate {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearCustomer clears the "customer" edge to the Customer entity.
func (_u *ProjectUpdate) ClearCustomer() *ProjectUpdate {
	_u.mutation.ClearCustomer()
	return _u
}

// ClearTeams clears all "teams" edges to the Team entity.
func (_u *ProjectUpdate) ClearTeams() *ProjectUpdate {
	_u.mutation.ClearTeams()
	return _u
}

// RemoveTeamIDs removes the "teams" edge to Team entities by IDs.
func (_u *ProjectUpdate) RemoveTeamIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveTeamIDs(ids...)
	return _u
}

// RemoveTeams removes "teams" edges to Team entities.
func (_u *ProjectUpdate) RemoveTeams(v ...*Team) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamIDs(ids...)
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *ProjectUpdate) ClearTasks() *ProjectUpdate {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *ProjectUpdate) RemoveTaskIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *ProjectUpdate) RemoveTasks(v ...*Task) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// ClearWorkSessions clears all "work_sessions" edges to the WorkSession entity.
func (_u *ProjectUpdate) ClearWorkSessions() *ProjectUpdate {
	_u.mutation.ClearWorkSessions()
	return _u
}

// RemoveWorkSessionIDs removes the "work_sessions" edge to WorkSession entities by IDs.
func (_u *ProjectUpdate) RemoveWorkSessionIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveWorkSessionIDs(ids...)
	return _u
}

// RemoveWorkSessions removes "work_sessions" edges to WorkSession entities.
func (_u *ProjectUpdate) RemoveWorkSessions(v ...*WorkSession) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWorkSessionIDs(ids...)
}

// ClearIntegrations clears all "integrations" edges to the Integration entity.
func (_u *ProjectUpdate) ClearIntegrations() *ProjectUpdate {
	_u.mutation.ClearIntegrations()
	return _u
}

// RemoveIntegrationIDs removes the "integrations" edge to Integration entities by IDs.
func (_u *ProjectUpdate) RemoveIntegrationIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveIntegrationIDs(ids...)
	return _u
}

// RemoveIntegrations removes "integrations" edges to Integration entities.
func (_u *ProjectUpdate) RemoveIntegrations(v ...*Integration) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIntegrationIDs(ids...)
}

// ClearAllocations clears all "allocations" edges to the Allocation entity.
func (_u *ProjectUpdate) ClearAllocations() *ProjectUpdate {
	_u.mutation.ClearAllocations()
	return _u
}

// RemoveAllocationIDs removes the "allocations" edge to Allocation entities by IDs.
func (_u *ProjectUpdate) RemoveAllocationIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveAllocationIDs(ids...)
	return _u
}

// RemoveAllocations removes "allocations" edges to Allocation entities.
func (_u *ProjectUpdate) RemoveAllocations(v ...*Allocation) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAllocationIDs(ids...)
}

// ClearInvites clears all "invites" edges to the Invite entity.
func (_u *ProjectUpdate) ClearInvites() *ProjectUpdate {
	_u.mutation.ClearInvites()
	return _u
}

// RemoveInviteIDs removes the "invites" edge to Invite entities by IDs.
func (_u *ProjectUpdate) RemoveInviteIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveInviteIDs(ids...)
	return _u
}

// RemoveInvites removes "invites" edges to Invite entities.
func (_u *ProjectUpdate) RemoveInvites(v ...*Invite) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInviteIDs(ids...)
}

// ClearLabels clears all "labels" edges to the Label entity.
func (_u *ProjectUpdate) ClearLabels() *ProjectUpdate {
	_u.mutation.ClearLabels()
	return _u
}

// RemoveLabelIDs removes the "labels" edge to Label entities by IDs.
func (_u *ProjectUpdate) RemoveLabelIDs(ids ...uuid.UUID) *ProjectUpdate {
	_u.mutation.RemoveLabelIDs(ids...)
	return _u
}

// RemoveLabels removes "labels" edges to Label entities.
func (_u *ProjectUpdate) RemoveLabels(v ...*Label) *ProjectUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLabelIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdate) check() error {
	if v, ok := _u.mutation.BillRateCents(); ok {
		if err := project.BillRateCentsValidator(v); err != nil {
			return &ValidationError{Name: "bill_rate_cents", err: fmt.Errorf(`ent: validator failed for field "Project.bill_rate_cents": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Project.organization"`)
	}
	return nil
}

func (_u *ProjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(project.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(project.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.GithubRepoURL(); ok {
		_spec.SetField(project.FieldGithubRepoURL, field.TypeString, value)
	}
	if _u.mutation.GithubRepoURLCleared() {
		_spec.ClearField(project.FieldGithubRepoURL, field.TypeString)
	}
	if value, ok := _u.mutation.GitlabRepoURL(); ok {
		_spec.SetField(project.FieldGitlabRepoURL, field.TypeString, value)
	}
	if _u.mutation.GitlabRepoURLCleared() {
		_spec.ClearField(project.FieldGitlabRepoURL, field.TypeString)
	}
	if value, ok := _u.mutation.SprintDurationDays(); ok {
		_spec.SetField(project.FieldSprintDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSprintDurationDays(); ok {
		_spec.AddField(project.FieldSprintDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DailyTime(); ok {
		_spec.SetField(project.FieldDailyTime, field.TypeString, value)
	}
	if _u.mutation.DailyTimeCleared() {
		_spec.ClearField(project.FieldDailyTime, field.TypeString)
	}
	if value, ok := _u.mutation.WeeklySyncDay(); ok {
		_spec.SetField(project.FieldWeeklySyncDay, field.TypeString, value)
	}
	if _u.mutation.WeeklySyncDayCleared() {
		_spec.ClearField(project.FieldWeeklySyncDay, field.TypeString)
	}
	if value, ok := _u.mutation.WeeklySyncTime(); ok {
		_spec.SetField(project.FieldWeeklySyncTime, field.TypeString, value)
	}
	if _u.mutation.WeeklySyncTimeCleared() {
		_spec.ClearField(project.FieldWeeklySyncTime, field.TypeString)
	}
	if value, ok := _u.mutation.CustomerMeetingDay(); ok {
		_spec.SetField(project.FieldCustomerMeetingDay, field.TypeString, value)
	}
	if _u.mutation.CustomerMeetingDayCleared() {
		_spec.ClearField(project.FieldCustomerMeetingDay, field.TypeString)
	}
	if value, ok := _u.mutation.CustomerMeetingTime(); ok {
		_spec.SetField(project.FieldCustomerMeetingTime, field.TypeString, value)
	}
	if _u.mutation.CustomerMeetingTimeCleared() {
		_spec.ClearField(project.FieldCustomerMeetingTime, field.TypeString)
	}
	if value, ok := _u.mutation.BillRateCents(); ok {
		_spec.SetField(project.FieldBillRateCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBillRateCents(); ok {
		_spec.AddField(project.FieldBillRateCents, field.TypeInt, value)
	}
	if _u.mutation.BillRateCentsCleared() {
		_spec.ClearField(project.FieldBillRateCents, field.TypeInt)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.OrganizationTable,
			Columns: []string{project.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.OrganizationTable,
			Columns: []string{project.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.CustomerTable,
			Columns: []string{project.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.CustomerTable,
			Columns: []string{project.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TeamsTable,
			Columns: []string{project.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamsIDs(); len(nodes) > 0 && !_u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TeamsTable,
			Columns: []string{project.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TeamsTable,
			Columns: []string{project.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TasksTable,
			Columns: []string{project.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TasksTable,
			Columns: []string{project.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TasksTable,
			Columns: []string{project.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WorkSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.WorkSessionsTable,
			Columns: []string{project.WorkSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worksession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWorkSessionsIDs(); len(nodes) > 0 && !_u.mutation.WorkSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.WorkSessionsTable,
			Columns: []string{project.WorkSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worksession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.WorkSessionsTable,
			Columns: []string{project.WorkSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worksession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IntegrationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.IntegrationsTable,
			Columns: []string{project.IntegrationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIntegrationsIDs(); len(nodes) > 0 && !_u.mutation.IntegrationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.IntegrationsTable,
			Columns: []string{project.IntegrationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IntegrationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.IntegrationsTable,
			Columns: []string{project.IntegrationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.AllocationsTable,
			Columns: []string{project.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(allocation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAllocationsIDs(); len(nodes) > 0 && !_u.mutation.AllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.AllocationsTable,
			Columns: []string{project.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(allocation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AllocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.AllocationsTable,
			Columns: []string{project.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(allocation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.InvitesTable,
			Columns: []string{project.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvitesIDs(); len(nodes) > 0 && !_u.mutation.InvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.InvitesTable,
			Columns: []string{project.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.InvitesTable,
			Columns: []string{project.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LabelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.LabelsTable,
			Columns: []string{project.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLabelsIDs(); len(nodes) > 0 && !_u.mutation.LabelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.LabelsTable,
			Columns: []string{project.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LabelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.LabelsTable,
			Columns: []string{project.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectUpdateOne is the builder for updating a single Project entity.
type ProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMutation
}

// SetOrganizationID sets the "organization_id" field.
func (_u *ProjectUpdateOne) SetOrganizationID(v uuid.UUID) *ProjectUpdateOne {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableOrganizationID(v *uuid.UUID) *ProjectUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ProjectUpdateOne) SetName(v string) *ProjectUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableName(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProjectUpdateOne) SetDescription(v string) *ProjectUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableDescription(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProjectUpdateOne) ClearDescription() *ProjectUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetGithubRepoURL sets the "github_repo_url" field.
func (_u *ProjectUpdateOne) SetGithubRepoURL(v string) *ProjectUpdateOne {
	_u.mutation.SetGithubRepoURL(v)
	return _u
}

// SetNillableGithubRepoURL sets the "github_repo_url" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableGithubRepoURL(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetGithubRepoURL(*v)
	}
	return _u
}

// ClearGithubRepoURL clears the value of the "github_repo_url" field.
func (_u *ProjectUpdateOne) ClearGithubRepoURL() *ProjectUpdateOne {
	_u.mutation.ClearGithubRepoURL()
	return _u
}

// SetGitlabRepoURL sets the "gitlab_repo_url" field.
func (_u *ProjectUpdateOne) SetGitlabRepoURL(v string) *ProjectUpdateOne {
	_u.mutation.SetGitlabRepoURL(v)
	return _u
}

// SetNillableGitlabRepoURL sets the "gitlab_repo_url" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableGitlabRepoURL(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetGitlabRepoURL(*v)
	}
	return _u
}

// ClearGitlabRepoURL clears the value of the "gitlab_repo_url" field.
func (_u *ProjectUpdateOne) ClearGitlabRepoURL() *ProjectUpdateOne {
	_u.mutation.ClearGitlabRepoURL()
	return _u
}

// SetSprintDurationDays sets the "sprint_duration_days" field.
func (_u *ProjectUpdateOne) SetSprintDurationDays(v int) *ProjectUpdateOne {
	_u.mutation.ResetSprintDurationDays()
	_u.mutation.SetSprintDurationDays(v)
	return _u
}

// SetNillableSprintDurationDays sets the "sprint_duration_days" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableSprintDurationDays(v *int) *ProjectUpdateOne {
	if v != nil {
		_u.SetSprintDurationDays(*v)
	}
	return _u
}

// AddSprintDurationDays adds value to the "sprint_duration_days" field.
func (_u *ProjectUpdateOne) AddSprintDurationDays(v int) *ProjectUpdateOne {
	_u.mutation.AddSprintDurationDays(v)
	return _u
}

// SetDailyTime sets the "daily_time" field.
func (_u *ProjectUpdateOne) SetDailyTime(v string) *ProjectUpdateOne {
	_u.mutation.SetDailyTime(v)
	return _u
}

// SetNillableDailyTime sets the "daily_time" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableDailyTime(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetDailyTime(*v)
	}
	return _u
}

// ClearDailyTime clears the value of the "daily_time" field.
func (_u *ProjectUpdateOne) ClearDailyTime() *ProjectUpdateOne {
	_u.mutation.ClearDailyTime()
	return _u
}

// SetWeeklySyncDay sets the "weekly_sync_day" field.
func (_u *ProjectUpdateOne) SetWeeklySyncDay(v string) *ProjectUpdateOne {
	_u.mutation.SetWeeklySyncDay(v)
	return _u
}

// SetNillableWeeklySyncDay sets the "weekly_sync_day" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableWeeklySyncDay(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetWeeklySyncDay(*v)
	}
	return _u
}

// ClearWeeklySyncDay clears the value of the "weekly_sync_day" field.
func (_u *ProjectUpdateOne) ClearWeeklySyncDay() *ProjectUpdateOne {
	_u.mutation.ClearWeeklySyncDay()
	return _u
}

// SetWeeklySyncTime sets the "weekly_sync_time" field.
func (_u *ProjectUpdateOne) SetWeeklySyncTime(v string) *ProjectUpdateOne {
	_u.mutation.SetWeeklySyncTime(v)
	return _u
}

// SetNillableWeeklySyncTime sets the "weekly_sync_time" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableWeeklySyncTime(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetWeeklySyncTime(*v)
	}
	return _u
}

// ClearWeeklySyncTime clears the value of the "weekly_sync_time" field.
func (_u *ProjectUpdateOne) ClearWeeklySyncTime() *ProjectUpdateOne {
	_u.mutation.ClearWeeklySyncTime()
	return _u
}

// SetCustomerMeetingDay sets the "customer_meeting_day" field.
func (_u *ProjectUpdateOne) SetCustomerMeetingDay(v string) *ProjectUpdateOne {
	_u.mutation.SetCustomerMeetingDay(v)
	return _u
}

// SetNillableCustomerMeetingDay sets the "customer_meeting_day" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableCustomerMeetingDay(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetCustomerMeetingDay(*v)
	}
	return _u
}

// ClearCustomerMeetingDay clears the value of the "customer_meeting_day" field.
func (_u *ProjectUpdateOne) ClearCustomerMeetingDay() *ProjectUpdateOne {
	_u.mutation.ClearCustomerMeetingDay()
	return _u
}

// SetCustomerMeetingTime sets the "customer_meeting_time" field.
func (_u *ProjectUpdateOne) SetCustomerMeetingTime(v string) *ProjectUpdateOne {
	_u.mutation.SetCustomerMeetingTime(v)
	return _u
}

// SetNillableCustomerMeetingTime sets the "customer_meeting_time" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableCustomerMeetingTime(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetCustomerMeetingTime(*v)
	}
	return _u
}

// ClearCustomerMeetingTime clears the value of the "customer_meeting_time" field.
func (_u *ProjectUpdateOne) ClearCustomerMeetingTime() *ProjectUpdateOne {
	_u.mutation.ClearCustomerMeetingTime()
	return _u
}

// SetCustomerID sets the "customer_id" field.
func (_u *ProjectUpdateOne) SetCustomerID(v uuid.UUID) *ProjectUpdateOne {
	_u.mutation.SetCustomerID(v)
	return _u
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableCustomerID(v *uuid.UUID) *ProjectUpdateOne {
	if v != nil {
		_u.SetCustomerID(*v)
	}
	return _u
}

// ClearCustomerID clears the value of the "customer_id" field.
func (_u *ProjectUpdateOne) ClearCustomerID() *ProjectUpdateOne {
	_u.mutation.ClearCustomerID()
	return _u
}

// SetBillRateCents sets the "bill_rate_cents" field.
func (_u *ProjectUpdateOne) SetBillRateCents(v int) *ProjectUpdateOne {
	_u.mutation.ResetBillRateCents()
	_u.mutation.SetBillRateCents(v)
	return _u
}

// SetNillableBillRateCents sets the "bill_rate_cents" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableBillRateCents(v *int) *ProjectUpdateOne {
	if v != nil {
		_u.SetBillRateCents(*v)
	}
	return _u
}

// AddBillRateCents adds value to the "bill_rate_cents" field.
func (_u *ProjectUpdateOne) AddBillRateCents(v int) *ProjectUpdateOne {
	_u.mutation.AddBillRateCents(v)
	return _u
}

// ClearBillRateCents clears the value of the "bill_rate_cents" field.
func (_u *ProjectUpdateOne) ClearBillRateCents() *ProjectUpdateOne {
	_u.mutation.ClearBillRateCents()
	return _u
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_u *ProjectUpdateOne) SetOrganization(v *Organization) *ProjectUpdateOne {
	return _u.SetOrganizationID(v.ID)
}

// SetCustomer sets the "customer" edge to the Customer entity.
func (_u *ProjectUpdateOne) SetCustomer(v *Customer) *ProjectUpdateOne {
	return _u.SetCustomerID(v.ID)
}

// AddTeamIDs adds the "teams" edge to the Team entity by IDs.
func (_u *ProjectUpdateOne) AddTeamIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddTeamIDs(ids...)
	return _u
}

// AddTeams adds the "teams" edges to the Team entity.
func (_u *ProjectUpdateOne) AddTeams(v ...*Team) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTeamIDs(ids...)
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *ProjectUpdateOne) AddTaskIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *ProjectUpdateOne) AddTasks(v ...*Task) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// AddWorkSessionIDs adds the "work_sessions" edge to the WorkSession entity by IDs.
func (_u *ProjectUpdateOne) AddWorkSessionIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddWorkSessionIDs(ids...)
	return _u
}

// AddWorkSessions adds the "work_sessions" edges to the WorkSession entity.
func (_u *ProjectUpdateOne) AddWorkSessions(v ...*WorkSession) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWorkSessionIDs(ids...)
}

// AddIntegrationIDs adds the "integrations" edge to the Integration entity by IDs.
func (_u *ProjectUpdateOne) AddIntegrationIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddIntegrationIDs(ids...)
	return _u
}

// AddIntegrations adds the "integrations" edges to the Integration entity.
func (_u *ProjectUpdateOne) AddIntegrations(v ...*Integration) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIntegrationIDs(ids...)
}

// AddAllocationIDs adds the "allocations" edge to the Allocation entity by IDs.
func (_u *ProjectUpdateOne) AddAllocationIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddAllocationIDs(ids...)
	return _u
}

// AddAllocations adds the "allocations" edges to the Allocation entity.
func (_u *ProjectUpdateOne) AddAllocations(v ...*Allocation) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAllocationIDs(ids...)
}

// AddInviteIDs adds the "invites" edge to the Invite entity by IDs.
func (_u *ProjectUpdateOne) AddInviteIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddInviteIDs(ids...)
	return _u
}

// AddInvites adds the "invites" edges to the Invite entity.
func (_u *ProjectUpdateOne) AddInvites(v ...*Invite) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInviteIDs(ids...)
}

// AddLabelIDs adds the "labels" edge to the Label entity by IDs.
func (_u *ProjectUpdateOne) AddLabelIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.AddLabelIDs(ids...)
	return _u
}

// AddLabels adds the "labels" edges to the Label entity.
func (_u *ProjectUpdateOne) AddLabels(v ...*Label) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLabelIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdateOne) Mutation() *ProjectMutation {
	return _u.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (_u *ProjectUpdateOne) ClearOrganization() *ProjectUpdateOne {
	_u.mutation.ClearOrganization()
	return _u
}

// ClearCustomer clears the "customer" edge to the Customer entity.
func (_u *ProjectUpdateOne) ClearCustomer() *ProjectUpdateOne {
	_u.mutation.ClearCustomer()
	return _u
}

// ClearTeams clears all "teams" edges to the Team entity.
func (_u *ProjectUpdateOne) ClearTeams() *ProjectUpdateOne {
	_u.mutation.ClearTeams()
	return _u
}

// RemoveTeamIDs removes the "teams" edge to Team entities by IDs.
func (_u *ProjectUpdateOne) RemoveTeamIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveTeamIDs(ids...)
	return _u
}

// RemoveTeams removes "teams" edges to Team entities.
func (_u *ProjectUpdateOne) RemoveTeams(v ...*Team) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTeamIDs(ids...)
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *ProjectUpdateOne) ClearTasks() *ProjectUpdateOne {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *ProjectUpdateOne) RemoveTaskIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *ProjectUpdateOne) RemoveTasks(v ...*Task) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// ClearWorkSessions clears all "work_sessions" edges to the WorkSession entity.
func (_u *ProjectUpdateOne) ClearWorkSessions() *ProjectUpdateOne {
	_u.mutation.ClearWorkSessions()
	return _u
}

// RemoveWorkSessionIDs removes the "work_sessions" edge to WorkSession entities by IDs.
func (_u *ProjectUpdateOne) RemoveWorkSessionIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveWorkSessionIDs(ids...)
	return _u
}

// RemoveWorkSessions removes "work_sessions" edges to WorkSession entities.
func (_u *ProjectUpdateOne) RemoveWorkSessions(v ...*WorkSession) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWorkSessionIDs(ids...)
}

// ClearIntegrations clears all "integrations" edges to the Integration entity.
func (_u *ProjectUpdateOne) ClearIntegrations() *ProjectUpdateOne {
	_u.mutation.ClearIntegrations()
	return _u
}

// RemoveIntegrationIDs removes the "integrations" edge to Integration entities by IDs.
func (_u *ProjectUpdateOne) RemoveIntegrationIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveIntegrationIDs(ids...)
	return _u
}

// RemoveIntegrations removes "integrations" edges to Integration entities.
func (_u *ProjectUpdateOne) RemoveIntegrations(v ...*Integration) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIntegrationIDs(ids...)
}

// ClearAllocations clears all "allocations" edges to the Allocation entity.
func (_u *ProjectUpdateOne) ClearAllocations() *ProjectUpdateOne {
	_u.mutation.ClearAllocations()
	return _u
}

// RemoveAllocationIDs removes the "allocations" edge to Allocation entities by IDs.
func (_u *ProjectUpdateOne) RemoveAllocationIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveAllocationIDs(ids...)
	return _u
}

// RemoveAllocations removes "allocations" edges to Allocation entities.
func (_u *ProjectUpdateOne) RemoveAllocations(v ...*Allocation) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAllocationIDs(ids...)
}

// ClearInvites clears all "invites" edges to the Invite entity.
func (_u *ProjectUpdateOne) ClearInvites() *ProjectUpdateOne {
	_u.mutation.ClearInvites()
	return _u
}

// RemoveInviteIDs removes the "invites" edge to Invite entities by IDs.
func (_u *ProjectUpdateOne) RemoveInviteIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveInviteIDs(ids...)
	return _u
}

// RemoveInvites removes "invites" edges to Invite entities.
func (_u *ProjectUpdateOne) RemoveInvites(v ...*Invite) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInviteIDs(ids...)
}

// ClearLabels clears all "labels" edges to the Label entity.
func (_u *ProjectUpdateOne) ClearLabels() *ProjectUpdateOne {
	_u.mutation.ClearLabels()
	return _u
}

// RemoveLabelIDs removes the "labels" edge to Label entities by IDs.
func (_u *ProjectUpdateOne) RemoveLabelIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	_u.mutation.RemoveLabelIDs(ids...)
	return _u
}

// RemoveLabels removes "labels" edges to Label entities.
func (_u *ProjectUpdateOne) RemoveLabels(v ...*Label) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLabelIDs(ids...)
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdateOne) Where(ps ...predicate.Project) *ProjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectUpdateOne) Select(field string, fields ...string) *ProjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Project entity.
func (_u *ProjectUpdateOne) Save(ctx context.Context) (*Project, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdateOne) SaveX(ctx context.Context) *Project {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProjectUpdateOne) check() error {
	if v, ok := _u.mutation.BillRateCents(); ok {
		if err := project.BillRateCentsValidator(v); err != nil {
			return &ValidationError{Name: "bill_rate_cents", err: fmt.Errorf(`ent: validator failed for field "Project.bill_rate_cents": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Project.organization"`)
	}
	return nil
}

func (_u *ProjectUpdateOne) sqlSave(ctx context.Context) (_node *Project, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Project.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, project.FieldID)
		for _, f := range fields {
			if !project.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != project.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(project.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(project.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.GithubRepoURL(); ok {
		_spec.SetField(project.FieldGithubRepoURL, field.TypeString, value)
	}
	if _u.mutation.GithubRepoURLCleared() {
		_spec.ClearField(project.FieldGithubRepoURL, field.TypeString)
	}
	if value, ok := _u.mutation.GitlabRepoURL(); ok {
		_spec.SetField(project.FieldGitlabRepoURL, field.TypeString, value)
	}
	if _u.mutation.GitlabRepoURLCleared() {
		_spec.ClearField(project.FieldGitlabRepoURL, field.TypeString)
	}
	if value, ok := _u.mutation.SprintDurationDays(); ok {
		_spec.SetField(project.FieldSprintDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSprintDurationDays(); ok {
		_spec.AddField(project.FieldSprintDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DailyTime(); ok {
		_spec.SetField(project.FieldDailyTime, field.TypeString, value)
	}
	if _u.mutation.DailyTimeCleared() {
		_spec.ClearField(project.FieldDailyTime, field.TypeString)
	}
	if value, ok := _u.mutation.WeeklySyncDay(); ok {
		_spec.SetField(project.FieldWeeklySyncDay, field.TypeString, value)
	}
	if _u.mutation.WeeklySyncDayCleared() {
		_spec.ClearField(project.FieldWeeklySyncDay, field.TypeString)
	}
	if value, ok := _u.mutation.WeeklySyncTime(); ok {
		_spec.SetField(project.FieldWeeklySyncTime, field.TypeString, value)
	}
	if _u.mutation.WeeklySyncTimeCleared() {
		_spec.ClearField(project.FieldWeeklySyncTime, field.TypeString)
	}
	if value, ok := _u.mutation.CustomerMeetingDay(); ok {
		_spec.SetField(project.FieldCustomerMeetingDay, field.TypeString, value)
	}
	if _u.mutation.CustomerMeetingDayCleared() {
		_spec.ClearField(project.FieldCustomerMeetingDay, field.TypeString)
	}
	if value, ok := _u.mutation.CustomerMeetingTime(); ok {
		_spec.SetField(project.FieldCustomerMeetingTime, field.TypeString, value)
	}
	if _u.mutation.CustomerMeetingTimeCleared() {
		_spec.ClearField(project.FieldCustomerMeetingTime, field.TypeString)
	}
	if value, ok := _u.mutation.BillRateCents(); ok {
		_spec.SetField(project.FieldBillRateCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBillRateCents(); ok {
		_spec.AddField(project.FieldBillRateCents, field.TypeInt, value)
	}
	if _u.mutation.BillRateCentsCleared() {
		_spec.ClearField(project.FieldBillRateCents, field.TypeInt)
	}
	if _u.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.OrganizationTable,
			Columns: []string{project.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.OrganizationTable,
			Columns: []string{project.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.CustomerTable,
			Columns: []string{project.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.CustomerTable,
			Columns: []string{project.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TeamsTable,
			Columns: []string{project.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTeamsIDs(); len(nodes) > 0 && !_u.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TeamsTable,
			Columns: []string{project.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TeamsTable,
			Columns: []string{project.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TasksTable,
			Columns: []string{project.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TasksTable,
			Columns: []string{project.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.TasksTable,
			Columns: []string{project.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WorkSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.WorkSessionsTable,
			Columns: []string{project.WorkSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worksession.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWorkSessionsIDs(); len(nodes) > 0 && !_u.mutation.WorkSessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.WorkSessionsTable,
			Columns: []string{project.WorkSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worksession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkSessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.WorkSessionsTable,
			Columns: []string{project.WorkSessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worksession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IntegrationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.IntegrationsTable,
			Columns: []string{project.IntegrationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIntegrationsIDs(); len(nodes) > 0 && !_u.mutation.IntegrationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.IntegrationsTable,
			Columns: []string{project.IntegrationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IntegrationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.IntegrationsTable,
			Columns: []string{project.IntegrationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.AllocationsTable,
			Columns: []string{project.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(allocation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAllocationsIDs(); len(nodes) > 0 && !_u.mutation.AllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.AllocationsTable,
			Columns: []string{project.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(allocation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AllocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.AllocationsTable,
			Columns: []string{project.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(allocation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.InvitesTable,
			Columns: []string{project.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInvitesIDs(); len(nodes) > 0 && !_u.mutation.InvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.InvitesTable,
			Columns: []string{project.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InvitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.InvitesTable,
			Columns: []string{project.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LabelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.LabelsTable,
			Columns: []string{project.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLabelsIDs(); len(nodes) > 0 && !_u.mutation.LabelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.LabelsTable,
			Columns: []string{project.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LabelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.LabelsTable,
			Columns: []string{project.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Project{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
