// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"working-time-tracker/ent/allocation"
	"working-time-tracker/ent/customer"
	"working-time-tracker/ent/integration"
	"working-time-tracker/ent/invite"
	"working-time-tracker/ent/organization"
	"working-time-tracker/ent/person"
	"working-time-tracker/ent/project"
	"working-time-tracker/ent/schema"
	"working-time-tracker/ent/session"
	"working-time-tracker/ent/task"
	"working-time-tracker/ent/team"
	"working-time-tracker/ent/teammembership"
	"working-time-tracker/ent/worksession"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	allocationFields := schema.Allocation{}.Fields()
	_ = allocationFields
	// allocationDescPayRateCents is the schema descriptor for pay_rate_cents field.
	allocationDescPayRateCents := allocationFields[3].Descriptor()
	// allocation.PayRateCentsValidator is a validator for the "pay_rate_cents" field. It is called by the builders before save.
	allocation.PayRateCentsValidator = allocationDescPayRateCents.Validators[0].(func(int) error)
	// allocationDescCreatedAt is the schema descriptor for created_at field.
	allocationDescCreatedAt := allocationFields[4].Descriptor()
	// allocation.DefaultCreatedAt holds the default value on creation for the created_at field.
	allocation.DefaultCreatedAt = allocationDescCreatedAt.Default.(func() time.Time)
	// allocationDescID is the schema descriptor for id field.
	allocationDescID := allocationFields[0].Descriptor()
	// allocation.DefaultID holds the default value on creation for the id field.
	allocation.DefaultID = allocationDescID.Default.(func() uuid.UUID)
	customerFields := schema.Customer{}.Fields()
	_ = customerFields
	// customerDescCreatedAt is the schema descriptor for created_at field.
	customerDescCreatedAt := customerFields[7].Descriptor()
	// customer.DefaultCreatedAt holds the default value on creation for the created_at field.
	customer.DefaultCreatedAt = customerDescCreatedAt.Default.(func() time.Time)
	// customerDescID is the schema descriptor for id field.
	customerDescID := customerFields[0].Descriptor()
	// customer.DefaultID holds the default value on creation for the id field.
	customer.DefaultID = customerDescID.Default.(func() uuid.UUID)
	integrationFields := schema.Integration{}.Fields()
	_ = integrationFields
	// integrationDescEnabled is the schema descriptor for enabled field.
	integrationDescEnabled := integrationFields[6].Descriptor()
	// integration.DefaultEnabled holds the default value on creation for the enabled field.
	integration.DefaultEnabled = integrationDescEnabled.Default.(bool)
	// integrationDescCreatedAt is the schema descriptor for created_at field.
	integrationDescCreatedAt := integrationFields[7].Descriptor()
	// integration.DefaultCreatedAt holds the default value on creation for the created_at field.
	integration.DefaultCreatedAt = integrationDescCreatedAt.Default.(func() time.Time)
	// integrationDescID is the schema descriptor for id field.
	integrationDescID := integrationFields[0].Descriptor()
	// integration.DefaultID holds the default value on creation for the id field.
	integration.DefaultID = integrationDescID.Default.(func() uuid.UUID)
	inviteFields := schema.Invite{}.Fields()
	_ = inviteFields
	// inviteDescCreatedAt is the schema descriptor for created_at field.
	inviteDescCreatedAt := inviteFields[8].Descriptor()
	// invite.DefaultCreatedAt holds the default value on creation for the created_at field.
	invite.DefaultCreatedAt = inviteDescCreatedAt.Default.(func() time.Time)
	// inviteDescID is the schema descriptor for id field.
	inviteDescID := inviteFields[0].Descriptor()
	// invite.DefaultID holds the default value on creation for the id field.
	invite.DefaultID = inviteDescID.Default.(func() uuid.UUID)
	organizationFields := schema.Organization{}.Fields()
	_ = organizationFields
	// organizationDescTimezone is the schema descriptor for timezone field.
	organizationDescTimezone := organizationFields[21].Descriptor()
	// organization.DefaultTimezone holds the default value on creation for the timezone field.
	organization.DefaultTimezone = organizationDescTimezone.Default.(string)
	// organizationDescCurrency is the schema descriptor for currency field.
	organizationDescCurrency := organizationFields[22].Descriptor()
	// organization.DefaultCurrency holds the default value on creation for the currency field.
	organization.DefaultCurrency = organizationDescCurrency.Default.(string)
	// organizationDescCreatedAt is the schema descriptor for created_at field.
	organizationDescCreatedAt := organizationFields[23].Descriptor()
	// organization.DefaultCreatedAt holds the default value on creation for the created_at field.
	organization.DefaultCreatedAt = organizationDescCreatedAt.Default.(func() time.Time)
	// organizationDescID is the schema descriptor for id field.
	organizationDescID := organizationFields[0].Descriptor()
	// organization.DefaultID holds the default value on creation for the id field.
	organization.DefaultID = organizationDescID.Default.(func() uuid.UUID)
	personFields := schema.Person{}.Fields()
	_ = personFields
	// personDescCreatedAt is the schema descriptor for created_at field.
	personDescCreatedAt := personFields[7].Descriptor()
	// person.DefaultCreatedAt holds the default value on creation for the created_at field.
	person.DefaultCreatedAt = personDescCreatedAt.Default.(func() time.Time)
	// personDescID is the schema descriptor for id field.
	personDescID := personFields[0].Descriptor()
	// person.DefaultID holds the default value on creation for the id field.
	person.DefaultID = personDescID.Default.(func() uuid.UUID)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescSprintDurationDays is the schema descriptor for sprint_duration_days field.
	projectDescSprintDurationDays := projectFields[6].Descriptor()
	// project.DefaultSprintDurationDays holds the default value on creation for the sprint_duration_days field.
	project.DefaultSprintDurationDays = projectDescSprintDurationDays.Default.(int)
	// projectDescBillRateCents is the schema descriptor for bill_rate_cents field.
	projectDescBillRateCents := projectFields[11].Descriptor()
	// project.BillRateCentsValidator is a validator for the "bill_rate_cents" field. It is called by the builders before save.
	project.BillRateCentsValidator = projectDescBillRateCents.Validators[0].(func(int) error)
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[12].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescID is the schema descriptor for id field.
	projectDescID := projectFields[0].Descriptor()
	// project.DefaultID holds the default value on creation for the id field.
	project.DefaultID = projectDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[4].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[9].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescID is the schema descriptor for id field.
	taskDescID := taskFields[0].Descriptor()
	// task.DefaultID holds the default value on creation for the id field.
	task.DefaultID = taskDescID.Default.(func() uuid.UUID)
	teamFields := schema.Team{}.Fields()
	_ = teamFields
	// teamDescCreatedAt is the schema descriptor for created_at field.
	teamDescCreatedAt := teamFields[3].Descriptor()
	// team.DefaultCreatedAt holds the default value on creation for the created_at field.
	team.DefaultCreatedAt = teamDescCreatedAt.Default.(func() time.Time)
	// teamDescID is the schema descriptor for id field.
	teamDescID := teamFields[0].Descriptor()
	// team.DefaultID holds the default value on creation for the id field.
	team.DefaultID = teamDescID.Default.(func() uuid.UUID)
	teammembershipFields := schema.TeamMembership{}.Fields()
	_ = teammembershipFields
	// teammembershipDescCreatedAt is the schema descriptor for created_at field.
	teammembershipDescCreatedAt := teammembershipFields[2].Descriptor()
	// teammembership.DefaultCreatedAt holds the default value on creation for the created_at field.
	teammembership.DefaultCreatedAt = teammembershipDescCreatedAt.Default.(func() time.Time)
	worksessionFields := schema.WorkSession{}.Fields()
	_ = worksessionFields
	// worksessionDescPayRateCents is the schema descriptor for pay_rate_cents field.
	worksessionDescPayRateCents := worksessionFields[5].Descriptor()
	// worksession.PayRateCentsValidator is a validator for the "pay_rate_cents" field. It is called by the builders before save.
	worksession.PayRateCentsValidator = worksessionDescPayRateCents.Validators[0].(func(int) error)
	// worksessionDescBillRateCents is the schema descriptor for bill_rate_cents field.
	worksessionDescBillRateCents := worksessionFields[6].Descriptor()
	// worksession.BillRateCentsValidator is a validator for the "bill_rate_cents" field. It is called by the builders before save.
	worksession.BillRateCentsValidator = worksessionDescBillRateCents.Validators[0].(func(int) error)
	// worksessionDescCreatedAt is the schema descriptor for created_at field.
	worksessionDescCreatedAt := worksessionFields[7].Descriptor()
	// worksession.DefaultCreatedAt holds the default value on creation for the created_at field.
	worksession.DefaultCreatedAt = worksessionDescCreatedAt.Default.(func() time.Time)
	// worksessionDescID is the schema descriptor for id field.
	worksessionDescID := worksessionFields[0].Descriptor()
	// worksession.DefaultID holds the default value on creation for the id field.
	worksession.DefaultID = worksessionDescID.Default.(func() uuid.UUID)
}
