// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"working-time-tracker/ent/integration"
	"working-time-tracker/ent/issuesync"
	"working-time-tracker/ent/person"
	"working-time-tracker/ent/project"
	"working-time-tracker/ent/task"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Task is the model entity for the Task schema.
type Task struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID uuid.UUID `json:"project_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority task.Priority `json:"priority,omitempty"`
	// Status holds the value of the "status" field.
	Status task.Status `json:"status,omitempty"`
	// AssigneeID holds the value of the "assignee_id" field.
	AssigneeID *uuid.UUID `json:"assignee_id,omitempty"`
	// Deadline holds the value of the "deadline" field.
	Deadline time.Time `json:"deadline,omitempty"`
	// ExternalIntegrationID holds the value of the "external_integration_id" field.
	ExternalIntegrationID *uuid.UUID `json:"external_integration_id,omitempty"`
	// ExternalItemID holds the value of the "external_item_id" field.
	ExternalItemID *string `json:"external_item_id,omitempty"`
	// ExternalItemURL holds the value of the "external_item_url" field.
	ExternalItemURL *string `json:"external_item_url,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskQuery when eager-loading is set.
	Edges        TaskEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TaskEdges holds the relations/edges for other nodes in the graph.
type TaskEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Assignee holds the value of the assignee edge.
	Assignee *Person `json:"assignee,omitempty"`
	// ExternalIntegration holds the value of the external_integration edge.
	ExternalIntegration *Integration `json:"external_integration,omitempty"`
	// SessionLinks holds the value of the session_links edge.
	SessionLinks []*WorkSessionTask `json:"session_links,omitempty"`
	// Labels holds the value of the labels edge.
	Labels []*Label `json:"labels,omitempty"`
	// IssueSync holds the value of the issue_sync edge.
	IssueSync *IssueSync `json:"issue_sync,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// AssigneeOrErr returns the Assignee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) AssigneeOrErr() (*Person, error) {
	if e.Assignee != nil {
		return e.Assignee, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: person.Label}
	}
	return nil, &NotLoadedError{edge: "assignee"}
}

// ExternalIntegrationOrErr returns the ExternalIntegration value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) ExternalIntegrationOrErr() (*Integration, error) {
	if e.ExternalIntegration != nil {
		return e.ExternalIntegration, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: integration.Label}
	}
	return nil, &NotLoadedError{edge: "external_integration"}
}

// SessionLinksOrErr returns the SessionLinks value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) SessionLinksOrErr() ([]*WorkSessionTask, error) {
	if e.loadedTypes[3] {
		return e.SessionLinks, nil
	}
	return nil, &NotLoadedError{edge: "session_links"}
}

// LabelsOrErr returns the Labels value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) LabelsOrErr() ([]*Label, error) {
	if e.loadedTypes[4] {
		return e.Labels, nil
	}
	return nil, &NotLoadedError{edge: "labels"}
}

// IssueSyncOrErr returns the IssueSync value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) IssueSyncOrErr() (*IssueSync, error) {
	if e.IssueSync != nil {
		return e.IssueSync, nil
	} else if e.loadedTypes[5] {
		return nil, &NotFoundError{label: issuesync.Label}
	}
	return nil, &NotLoadedError{edge: "issue_sync"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Task) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case task.FieldAssigneeID, task.FieldExternalIntegrationID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case task.FieldName, task.FieldDescription, task.FieldPriority, task.FieldStatus, task.FieldExternalItemID, task.FieldExternalItemURL:
			values[i] = new(sql.NullString)
		case task.FieldDeadline, task.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case task.FieldID, task.FieldProjectID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Task fields.
func (_m *Task) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case task.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case task.FieldProjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value != nil {
				_m.ProjectID = *value
			}
		case task.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case task.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case task.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = task.Priority(value.String)
			}
		case task.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = task.Status(value.String)
			}
		case task.FieldAssigneeID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field assignee_id", values[i])
			} else if value.Valid {
				_m.AssigneeID = new(uuid.UUID)
				*_m.AssigneeID = *value.S.(*uuid.UUID)
			}
		case task.FieldDeadline:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deadline", values[i])
			} else if value.Valid {
				_m.Deadline = value.Time
			}
		case task.FieldExternalIntegrationID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field external_integration_id", values[i])
			} else if value.Valid {
				_m.ExternalIntegrationID = new(uuid.UUID)
				*_m.ExternalIntegrationID = *value.S.(*uuid.UUID)
			}
		case task.FieldExternalItemID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_item_id", values[i])
			} else if value.Valid {
				_m.ExternalItemID = new(string)
				*_m.ExternalItemID = value.String
			}
		case task.FieldExternalItemURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_item_url", values[i])
			} else if value.Valid {
				_m.ExternalItemURL = new(string)
				*_m.ExternalItemURL = value.String
			}
		case task.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Task.
// This includes values selected through modifiers, order, etc.
func (_m *Task) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the Task entity.
func (_m *Task) QueryProject() *ProjectQuery {
	return NewTaskClient(_m.config).QueryProject(_m)
}

// QueryAssignee queries the "assignee" edge of the Task entity.
func (_m *Task) QueryAssignee() *PersonQuery {
	return NewTaskClient(_m.config).QueryAssignee(_m)
}

// QueryExternalIntegration queries the "external_integration" edge of the Task entity.
func (_m *Task) QueryExternalIntegration() *IntegrationQuery {
	return NewTaskClient(_m.config).QueryExternalIntegration(_m)
}

// QuerySessionLinks queries the "session_links" edge of the Task entity.
func (_m *Task) QuerySessionLinks() *WorkSessionTaskQuery {
	return NewTaskClient(_m.config).QuerySessionLinks(_m)
}

// QueryLabels queries the "labels" edge of the Task entity.
func (_m *Task) QueryLabels() *LabelQuery {
	return NewTaskClient(_m.config).QueryLabels(_m)
}

// QueryIssueSync queries the "issue_sync" edge of the Task entity.
func (_m *Task) QueryIssueSync() *IssueSyncQuery {
	return NewTaskClient(_m.config).QueryIssueSync(_m)
}

// Update returns a builder for updating this Task.
// Note that you need to call Task.Unwrap() before calling this method if this Task
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Task) Update() *TaskUpdateOne {
	return NewTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Task entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Task) Unwrap() *Task {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Task is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Task) String() string {
	var builder strings.Builder
	builder.WriteString("Task(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.AssigneeID; v != nil {
		builder.WriteString("assignee_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("deadline=")
	builder.WriteString(_m.Deadline.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ExternalIntegrationID; v != nil {
		builder.WriteString("external_integration_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ExternalItemID; v != nil {
		builder.WriteString("external_item_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ExternalItemURL; v != nil {
		builder.WriteString("external_item_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Tasks is a parsable slice of Task.
type Tasks []*Task
