// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"working-time-tracker/ent/person"
	"working-time-tracker/ent/predicate"
	"working-time-tracker/ent/team"
	"working-time-tracker/ent/teammembership"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TeamMembershipUpdate is the builder for updating TeamMembership entities.
type TeamMembershipUpdate struct {
	config
	hooks    []Hook
	mutation *TeamMembershipMutation
}

// Where appends a list predicates to the TeamMembershipUpdate builder.
func (_u *TeamMembershipUpdate) Where(ps ...predicate.TeamMembership) *TeamMembershipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPersonID sets the "person_id" field.
func (_u *TeamMembershipUpdate) SetPersonID(v uuid.UUID) *TeamMembershipUpdate {
	_u.mutation.SetPersonID(v)
	return _u
}

// SetNillablePersonID sets the "person_id" field if the given value is not nil.
func (_u *TeamMembershipUpdate) SetNillablePersonID(v *uuid.UUID) *TeamMembershipUpdate {
	if v != nil {
		_u.SetPersonID(*v)
	}
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamMembershipUpdate) SetTeamID(v uuid.UUID) *TeamMembershipUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamMembershipUpdate) SetNillableTeamID(v *uuid.UUID) *TeamMembershipUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetPerson sets the "person" edge to the Person entity.
func (_u *TeamMembershipUpdate) SetPerson(v *Person) *TeamMembershipUpdate {
	return _u.SetPersonID(v.ID)
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamMembershipUpdate) SetTeam(v *Team) *TeamMembershipUpdate {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the TeamMembershipMutation object of the builder.
func (_u *TeamMembershipUpdate) Mutation() *TeamMembershipMutation {
	return _u.mutation
}

// ClearPerson clears the "person" edge to the Person entity.
func (_u *TeamMembershipUpdate) ClearPerson() *TeamMembershipUpdate {
	_u.mutation.ClearPerson()
	return _u
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamMembershipUpdate) ClearTeam() *TeamMembershipUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamMembershipUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamMembershipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamMembershipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamMembershipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamMembershipUpdate) check() error {
	if _u.mutation.PersonCleared() && len(_u.mutation.PersonIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamMembership.person"`)
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamMembership.team"`)
	}
	return nil
}

func (_u *TeamMembershipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teammembership.Table, teammembership.Columns, sqlgraph.NewFieldSpec(teammembership.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.PersonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.PersonTable,
			Columns: []string{teammembership.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.PersonTable,
			Columns: []string{teammembership.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.TeamTable,
			Columns: []string{teammembership.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.TeamTable,
			Columns: []string{teammembership.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teammembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamMembershipUpdateOne is the builder for updating a single TeamMembership entity.
type TeamMembershipUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamMembershipMutation
}

// SetPersonID sets the "person_id" field.
func (_u *TeamMembershipUpdateOne) SetPersonID(v uuid.UUID) *TeamMembershipUpdateOne {
	_u.mutation.SetPersonID(v)
	return _u
}

// SetNillablePersonID sets the "person_id" field if the given value is not nil.
func (_u *TeamMembershipUpdateOne) SetNillablePersonID(v *uuid.UUID) *TeamMembershipUpdateOne {
	if v != nil {
		_u.SetPersonID(*v)
	}
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *TeamMembershipUpdateOne) SetTeamID(v uuid.UUID) *TeamMembershipUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *TeamMembershipUpdateOne) SetNillableTeamID(v *uuid.UUID) *TeamMembershipUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetPerson sets the "person" edge to the Person entity.
func (_u *TeamMembershipUpdateOne) SetPerson(v *Person) *TeamMembershipUpdateOne {
	return _u.SetPersonID(v.ID)
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *TeamMembershipUpdateOne) SetTeam(v *Team) *TeamMembershipUpdateOne {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the TeamMembershipMutation object of the builder.
func (_u *TeamMembershipUpdateOne) Mutation() *TeamMembershipMutation {
	return _u.mutation
}

// ClearPerson clears the "person" edge to the Person entity.
func (_u *TeamMembershipUpdateOne) ClearPerson() *TeamMembershipUpdateOne {
	_u.mutation.ClearPerson()
	return _u
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *TeamMembershipUpdateOne) ClearTeam() *TeamMembershipUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// Where appends a list predicates to the TeamMembershipUpdate builder.
func (_u *TeamMembershipUpdateOne) Where(ps ...predicate.TeamMembership) *TeamMembershipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamMembershipUpdateOne) Select(field string, fields ...string) *TeamMembershipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TeamMembership entity.
func (_u *TeamMembershipUpdateOne) Save(ctx context.Context) (*TeamMembership, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamMembershipUpdateOne) SaveX(ctx context.Context) *TeamMembership {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamMembershipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamMembershipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamMembershipUpdateOne) check() error {
	if _u.mutation.PersonCleared() && len(_u.mutation.PersonIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamMembership.person"`)
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TeamMembership.team"`)
	}
	return nil
}

func (_u *TeamMembershipUpdateOne) sqlSave(ctx context.Context) (_node *TeamMembership, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teammembership.Table, teammembership.Columns, sqlgraph.NewFieldSpec(teammembership.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamMembership.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teammembership.FieldID)
		for _, f := range fields {
			if !teammembership.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teammembership.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.PersonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.PersonTable,
			Columns: []string{teammembership.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.PersonTable,
			Columns: []string{teammembership.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.TeamTable,
			Columns: []string{teammembership.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.TeamTable,
			Columns: []string{teammembership.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TeamMembership{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teammembership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
