// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"working-time-tracker/ent/person"
	"working-time-tracker/ent/team"
	"working-time-tracker/ent/teammembership"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TeamMembershipCreate is the builder for creating a TeamMembership entity.
type TeamMembershipCreate struct {
	config
	mutation *TeamMembershipMutation
	hooks    []Hook
}

// SetPersonID sets the "person_id" field.
func (_c *TeamMembershipCreate) SetPersonID(v uuid.UUID) *TeamMembershipCreate {
	_c.mutation.SetPersonID(v)
	return _c
}

// SetTeamID sets the "team_id" field.
func (_c *TeamMembershipCreate) SetTeamID(v uuid.UUID) *TeamMembershipCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TeamMembershipCreate) SetCreatedAt(v time.Time) *TeamMembershipCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableCreatedAt(v *time.Time) *TeamMembershipCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetPerson sets the "person" edge to the Person entity.
func (_c *TeamMembershipCreate) SetPerson(v *Person) *TeamMembershipCreate {
	return _c.SetPersonID(v.ID)
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *TeamMembershipCreate) SetTeam(v *Team) *TeamMembershipCreate {
	return _c.SetTeamID(v.ID)
}

// Mutation returns the TeamMembershipMutation object of the builder.
func (_c *TeamMembershipCreate) Mutation() *TeamMembershipMutation {
	return _c.mutation
}

// Save creates the TeamMembership in the database.
func (_c *TeamMembershipCreate) Save(ctx context.Context) (*TeamMembership, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamMembershipCreate) SaveX(ctx context.Context) *TeamMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamMembershipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamMembershipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamMembershipCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := teammembership.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamMembershipCreate) check() error {
	if _, ok := _c.mutation.PersonID(); !ok {
		return &ValidationError{Name: "person_id", err: errors.New(`ent: missing required field "TeamMembership.person_id"`)}
	}
	if _, ok := _c.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`ent: missing required field "TeamMembership.team_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TeamMembership.created_at"`)}
	}
	if len(_c.mutation.PersonIDs()) == 0 {
		return &ValidationError{Name: "person", err: errors.New(`ent: missing required edge "TeamMembership.person"`)}
	}
	if len(_c.mutation.TeamIDs()) == 0 {
		return &ValidationError{Name: "team", err: errors.New(`ent: missing required edge "TeamMembership.team"`)}
	}
	return nil
}

func (_c *TeamMembershipCreate) sqlSave(ctx context.Context) (*TeamMembership, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamMembershipCreate) createSpec() (*TeamMembership, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamMembership{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teammembership.Table, sqlgraph.NewFieldSpec(teammembership.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(teammembership.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.PersonTable,
			Columns: []string{teammembership.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PersonID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.TeamTable,
			Columns: []string{teammembership.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TeamMembershipCreateBulk is the builder for creating many TeamMembership entities in bulk.
type TeamMembershipCreateBulk struct {
	config
	err      error
	builders []*TeamMembershipCreate
}

// Save creates the TeamMembership entities in the database.
func (_c *TeamMembershipCreateBulk) Save(ctx context.Context) ([]*TeamMembership, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamMembership, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamMembershipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamMembershipCreateBulk) SaveX(ctx context.Context) []*TeamMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamMembershipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamMembershipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
