// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"working-time-tracker/ent/task"
	"working-time-tracker/ent/worksession"
	"working-time-tracker/ent/worksessiontask"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WorkSessionTaskCreate is the builder for creating a WorkSessionTask entity.
type WorkSessionTaskCreate struct {
	config
	mutation *WorkSessionTaskMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (_c *WorkSessionTaskCreate) SetSessionID(v uuid.UUID) *WorkSessionTaskCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *WorkSessionTaskCreate) SetTaskID(v uuid.UUID) *WorkSessionTaskCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetFromAt sets the "from_at" field.
func (_c *WorkSessionTaskCreate) SetFromAt(v time.Time) *WorkSessionTaskCreate {
	_c.mutation.SetFromAt(v)
	return _c
}

// SetUntilAt sets the "until_at" field.
func (_c *WorkSessionTaskCreate) SetUntilAt(v time.Time) *WorkSessionTaskCreate {
	_c.mutation.SetUntilAt(v)
	return _c
}

// SetNillableUntilAt sets the "until_at" field if the given value is not nil.
func (_c *WorkSessionTaskCreate) SetNillableUntilAt(v *time.Time) *WorkSessionTaskCreate {
	if v != nil {
		_c.SetUntilAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WorkSessionTaskCreate) SetCreatedAt(v time.Time) *WorkSessionTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WorkSessionTaskCreate) SetNillableCreatedAt(v *time.Time) *WorkSessionTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WorkSessionTaskCreate) SetID(v uuid.UUID) *WorkSessionTaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *WorkSessionTaskCreate) SetNillableID(v *uuid.UUID) *WorkSessionTaskCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetSession sets the "session" edge to the WorkSession entity.
func (_c *WorkSessionTaskCreate) SetSession(v *WorkSession) *WorkSessionTaskCreate {
	return _c.SetSessionID(v.ID)
}

// SetTask sets the "task" edge to the Task entity.
func (_c *WorkSessionTaskCreate) SetTask(v *Task) *WorkSessionTaskCreate {
	return _c.SetTaskID(v.ID)
}

// Mutation returns the WorkSessionTaskMutation object of the builder.
func (_c *WorkSessionTaskCreate) Mutation() *WorkSessionTaskMutation {
	return _c.mutation
}

// Save creates the WorkSessionTask in the database.
func (_c *WorkSessionTaskCreate) Save(ctx context.Context) (*WorkSessionTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WorkSessionTaskCreate) SaveX(ctx context.Context) *WorkSessionTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkSessionTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkSessionTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WorkSessionTaskCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := worksessiontask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := worksessiontask.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WorkSessionTaskCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "WorkSessionTask.session_id"`)}
	}
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "WorkSessionTask.task_id"`)}
	}
	if _, ok := _c.mutation.FromAt(); !ok {
		return &ValidationError{Name: "from_at", err: errors.New(`ent: missing required field "WorkSessionTask.from_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WorkSessionTask.created_at"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "WorkSessionTask.session"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "WorkSessionTask.task"`)}
	}
	return nil
}

func (_c *WorkSessionTaskCreate) sqlSave(ctx context.Context) (*WorkSessionTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WorkSessionTaskCreate) createSpec() (*WorkSessionTask, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkSessionTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(worksessiontask.Table, sqlgraph.NewFieldSpec(worksessiontask.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.FromAt(); ok {
		_spec.SetField(worksessiontask.FieldFromAt, field.TypeTime, value)
		_node.FromAt = value
	}
	if value, ok := _c.mutation.UntilAt(); ok {
		_spec.SetField(worksessiontask.FieldUntilAt, field.TypeTime, value)
		_node.UntilAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(worksessiontask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   worksessiontask.SessionTable,
			Columns: []string{worksessiontask.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worksession.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   worksessiontask.TaskTable,
			Columns: []string{worksessiontask.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WorkSessionTaskCreateBulk is the builder for creating many WorkSessionTask entities in bulk.
type WorkSessionTaskCreateBulk struct {
	config
	err      error
	builders []*WorkSessionTaskCreate
}

// Save creates the WorkSessionTask entities in the database.
func (_c *WorkSessionTaskCreateBulk) Save(ctx context.Context) ([]*WorkSessionTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WorkSessionTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkSessionTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WorkSessionTaskCreateBulk) SaveX(ctx context.Context) []*WorkSessionTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WorkSessionTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WorkSessionTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
