// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"working-time-tracker/ent/person"
	"working-time-tracker/ent/predicate"
	"working-time-tracker/ent/project"
	"working-time-tracker/ent/worksession"
	"working-time-tracker/ent/worksessiontask"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WorkSessionUpdate is the builder for updating WorkSession entities.
type WorkSessionUpdate struct {
	config
	hooks    []Hook
	mutation *WorkSessionMutation
}

// Where appends a list predicates to the WorkSessionUpdate builder.
func (_u *WorkSessionUpdate) Where(ps ...predicate.WorkSession) *WorkSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *WorkSessionUpdate) SetProjectID(v uuid.UUID) *WorkSessionUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *WorkSessionUpdate) SetNillableProjectID(v *uuid.UUID) *WorkSessionUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetPersonID sets the "person_id" field.
func (_u *WorkSessionUpdate) SetPersonID(v uuid.UUID) *WorkSessionUpdate {
	_u.mutation.SetPersonID(v)
	return _u
}

// SetNillablePersonID sets the "person_id" field if the given value is not nil.
func (_u *WorkSessionUpdate) SetNillablePersonID(v *uuid.UUID) *WorkSessionUpdate {
	if v != nil {
		_u.SetPersonID(*v)
	}
	return _u
}

// SetStartAt sets the "start_at" field.
func (_u *WorkSessionUpdate) SetStartAt(v time.Time) *WorkSessionUpdate {
	_u.mutation.SetStartAt(v)
	return _u
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (_u *WorkSessionUpdate) SetNillableStartAt(v *time.Time) *WorkSessionUpdate {
	if v != nil {
		_u.SetStartAt(*v)
	}
	return _u
}

// SetEndAt sets the "end_at" field.
func (_u *WorkSessionUpdate) SetEndAt(v time.Time) *WorkSessionUpdate {
	_u.mutation.SetEndAt(v)
	return _u
}

// SetNillableEndAt sets the "end_at" field if the given value is not nil.
func (_u *WorkSessionUpdate) SetNillableEndAt(v *time.Time) *WorkSessionUpdate {
	if v != nil {
		_u.SetEndAt(*v)
	}
	return _u
}

// ClearEndAt clears the value of the "end_at" field.
func (_u *WorkSessionUpdate) ClearEndAt() *WorkSessionUpdate {
	_u.mutation.ClearEndAt()
	return _u
}

// SetPayRateCents sets the "pay_rate_cents" field.
func (_u *WorkSessionUpdate) SetPayRateCents(v int) *WorkSessionUpdate {
	_u.mutation.ResetPayRateCents()
	_u.mutation.SetPayRateCents(v)
	return _u
}

// SetNillablePayRateCents sets the "pay_rate_cents" field if the given value is not nil.
func (_u *WorkSessionUpdate) SetNillablePayRateCents(v *int) *WorkSessionUpdate {
	if v != nil {
		_u.SetPayRateCents(*v)
	}
	return _u
}

// AddPayRateCents adds value to the "pay_rate_cents" field.
func (_u *WorkSessionUpdate) AddPayRateCents(v int) *WorkSessionUpdate {
	_u.mutation.AddPayRateCents(v)
	return _u
}

// ClearPayRateCents clears the value of the "pay_rate_cents" field.
func (_u *WorkSessionUpdate) ClearPayRateCents() *WorkSessionUpdate {
	_u.mutation.ClearPayRateCents()
	return _u
}

// SetBillRateCents sets the "bill_rate_cents" field.
func (_u *WorkSessionUpdate) SetBillRateCents(v int) *WorkSessionUpdate {
	_u.mutation.ResetBillRateCents()
	_u.mutation.SetBillRateCents(v)
	return _u
}

// SetNillableBillRateCents sets the "bill_rate_cents" field if the given value is not nil.
func (_u *WorkSessionUpdate) SetNillableBillRateCents(v *int) *WorkSessionUpdate {
	if v != nil {
		_u.SetBillRateCents(*v)
	}
	return _u
}

// AddBillRateCents adds value to the "bill_rate_cents" field.
func (_u *WorkSessionUpdate) AddBillRateCents(v int) *WorkSessionUpdate {
	_u.mutation.AddBillRateCents(v)
	return _u
}

// ClearBillRateCents clears the value of the "bill_rate_cents" field.
func (_u *WorkSessionUpdate) ClearBillRateCents() *WorkSessionUpdate {
	_u.mutation.ClearBillRateCents()
	return _u
}

// SetOwnerHours sets the "owner_hours" field.
func (_u *WorkSessionUpdate) SetOwnerHours(v bool) *WorkSessionUpdate {
	_u.mutation.SetOwnerHours(v)
	return _u
}

// SetNillableOwnerHours sets the "owner_hours" field if the given value is not nil.
func (_u *WorkSessionUpdate) SetNillableOwnerHours(v *bool) *WorkSessionUpdate {
	if v != nil {
		_u.SetOwnerHours(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *WorkSessionUpdate) SetProject(v *Project) *WorkSessionUpdate {
	return _u.SetProjectID(v.ID)
}

// SetPerson sets the "person" edge to the Person entity.
func (_u *WorkSessionUpdate) SetPerson(v *Person) *WorkSessionUpdate {
	return _u.SetPersonID(v.ID)
}

// AddTaskLinkIDs adds the "task_links" edge to the WorkSessionTask entity by IDs.
func (_u *WorkSessionUpdate) AddTaskLinkIDs(ids ...uuid.UUID) *WorkSessionUpdate {
	_u.mutation.AddTaskLinkIDs(ids...)
	return _u
}

// AddTaskLinks adds the "task_links" edges to the WorkSessionTask entity.
func (_u *WorkSessionUpdate) AddTaskLinks(v ...*WorkSessionTask) *WorkSessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskLinkIDs(ids...)
}

// Mutation returns the WorkSessionMutation object of the builder.
func (_u *WorkSessionUpdate) Mutation() *WorkSessionMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *WorkSessionUpdate) ClearProject() *WorkSessionUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearPerson clears the "person" edge to the Person entity.
func (_u *WorkSessionUpdate) ClearPerson() *WorkSessionUpdate {
	_u.mutation.ClearPerson()
	return _u
}

// ClearTaskLinks clears all "task_links" edges to the WorkSessionTask entity.
func (_u *WorkSessionUpdate) ClearTaskLinks() *WorkSessionUpdate {
	_u.mutation.ClearTaskLinks()
	return _u
}

// RemoveTaskLinkIDs removes the "task_links" edge to WorkSessionTask entities by IDs.
func (_u *WorkSessionUpdate) RemoveTaskLinkIDs(ids ...uuid.UUID) *WorkSessionUpdate {
	_u.mutation.RemoveTaskLinkIDs(ids...)
	return _u
}

// RemoveTaskLinks removes "task_links" edges to WorkSessionTask entities.
func (_u *WorkSessionUpdate) RemoveTaskLinks(v ...*WorkSessionTask) *WorkSessionUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskLinkIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkSessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkSessionUpdate) check() error {
	if v, ok := _u.mutation.PayRateCents(); ok {
		if err := worksession.PayRateCentsValidator(v); err != nil {
			return &ValidationError{Name: "pay_rate_cents", err: fmt.Errorf(`ent: validator failed for field "WorkSession.pay_rate_cents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillRateCents(); ok {
		if err := worksession.BillRateCentsValidator(v); err != nil {
			return &ValidationError{Name: "bill_rate_cents", err: fmt.Errorf(`ent: validator failed for field "WorkSession.bill_rate_cents": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkSession.project"`)
	}
	if _u.mutation.PersonCleared() && len(_u.mutation.PersonIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkSession.person"`)
	}
	return nil
}

func (_u *WorkSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(worksession.Table, worksession.Columns, sqlgraph.NewFieldSpec(worksession.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StartAt(); ok {
		_spec.SetField(worksession.FieldStartAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndAt(); ok {
		_spec.SetField(worksession.FieldEndAt, field.TypeTime, value)
	}
	if _u.mutation.EndAtCleared() {
		_spec.ClearField(worksession.FieldEndAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PayRateCents(); ok {
		_spec.SetField(worksession.FieldPayRateCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPayRateCents(); ok {
		_spec.AddField(worksession.FieldPayRateCents, field.TypeInt, value)
	}
	if _u.mutation.PayRateCentsCleared() {
		_spec.ClearField(worksession.FieldPayRateCents, field.TypeInt)
	}
	if value, ok := _u.mutation.BillRateCents(); ok {
		_spec.SetField(worksession.FieldBillRateCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBillRateCents(); ok {
		_spec.AddField(worksession.FieldBillRateCents, field.TypeInt, value)
	}
	if _u.mutation.BillRateCentsCleared() {
		_spec.ClearField(worksession.FieldBillRateCents, field.TypeInt)
	}
	if value, ok := _u.mutation.OwnerHours(); ok {
		_spec.SetField(worksession.FieldOwnerHours, field.TypeBool, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   worksession.ProjectTable,
			Columns: []string{worksession.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   worksession.ProjectTable,
			Columns: []string{worksession.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PersonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   worksession.PersonTable,
			Columns: []string{worksession.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   worksession.PersonTable,
			Columns: []string{worksession.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   worksession.TaskLinksTable,
			Columns: []string{worksession.TaskLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worksessiontask.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskLinksIDs(); len(nodes) > 0 && !_u.mutation.TaskLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   worksession.TaskLinksTable,
			Columns: []string{worksession.TaskLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worksessiontask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskLinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   worksession.TaskLinksTable,
			Columns: []string{worksession.TaskLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worksessiontask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{worksession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkSessionUpdateOne is the builder for updating a single WorkSession entity.
type WorkSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkSessionMutation
}

// SetProjectID sets the "project_id" field.
func (_u *WorkSessionUpdateOne) SetProjectID(v uuid.UUID) *WorkSessionUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *WorkSessionUpdateOne) SetNillableProjectID(v *uuid.UUID) *WorkSessionUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetPersonID sets the "person_id" field.
func (_u *WorkSessionUpdateOne) SetPersonID(v uuid.UUID) *WorkSessionUpdateOne {
	_u.mutation.SetPersonID(v)
	return _u
}

// SetNillablePersonID sets the "person_id" field if the given value is not nil.
func (_u *WorkSessionUpdateOne) SetNillablePersonID(v *uuid.UUID) *WorkSessionUpdateOne {
	if v != nil {
		_u.SetPersonID(*v)
	}
	return _u
}

// SetStartAt sets the "start_at" field.
func (_u *WorkSessionUpdateOne) SetStartAt(v time.Time) *WorkSessionUpdateOne {
	_u.mutation.SetStartAt(v)
	return _u
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (_u *WorkSessionUpdateOne) SetNillableStartAt(v *time.Time) *WorkSessionUpdateOne {
	if v != nil {
		_u.SetStartAt(*v)
	}
	return _u
}

// SetEndAt sets the "end_at" field.
func (_u *WorkSessionUpdateOne) SetEndAt(v time.Time) *WorkSessionUpdateOne {
	_u.mutation.SetEndAt(v)
	return _u
}

// SetNillableEndAt sets the "end_at" field if the given value is not nil.
func (_u *WorkSessionUpdateOne) SetNillableEndAt(v *time.Time) *WorkSessionUpdateOne {
	if v != nil {
		_u.SetEndAt(*v)
	}
	return _u
}

// ClearEndAt clears the value of the "end_at" field.
func (_u *WorkSessionUpdateOne) ClearEndAt() *WorkSessionUpdateOne {
	_u.mutation.ClearEndAt()
	return _u
}

// SetPayRateCents sets the "pay_rate_cents" field.
func (_u *WorkSessionUpdateOne) SetPayRateCents(v int) *WorkSessionUpdateOne {
	_u.mutation.ResetPayRateCents()
	_u.mutation.SetPayRateCents(v)
	return _u
}

// SetNillablePayRateCents sets the "pay_rate_cents" field if the given value is not nil.
func (_u *WorkSessionUpdateOne) SetNillablePayRateCents(v *int) *WorkSessionUpdateOne {
	if v != nil {
		_u.SetPayRateCents(*v)
	}
	return _u
}

// AddPayRateCents adds value to the "pay_rate_cents" field.
func (_u *WorkSessionUpdateOne) AddPayRateCents(v int) *WorkSessionUpdateOne {
	_u.mutation.AddPayRateCents(v)
	return _u
}

// ClearPayRateCents clears the value of the "pay_rate_cents" field.
func (_u *WorkSessionUpdateOne) ClearPayRateCents() *WorkSessionUpdateOne {
	_u.mutation.ClearPayRateCents()
	return _u
}

// SetBillRateCents sets the "bill_rate_cents" field.
func (_u *WorkSessionUpdateOne) SetBillRateCents(v int) *WorkSessionUpdateOne {
	_u.mutation.ResetBillRateCents()
	_u.mutation.SetBillRateCents(v)
	return _u
}

// SetNillableBillRateCents sets the "bill_rate_cents" field if the given value is not nil.
func (_u *WorkSessionUpdateOne) SetNillableBillRateCents(v *int) *WorkSessionUpdateOne {
	if v != nil {
		_u.SetBillRateCents(*v)
	}
	return _u
}

// AddBillRateCents adds value to the "bill_rate_cents" field.
func (_u *WorkSessionUpdateOne) AddBillRateCents(v int) *WorkSessionUpdateOne {
	_u.mutation.AddBillRateCents(v)
	return _u
}

// ClearBillRateCents clears the value of the "bill_rate_cents" field.
func (_u *WorkSessionUpdateOne) ClearBillRateCents() *WorkSessionUpdateOne {
	_u.mutation.ClearBillRateCents()
	return _u
}

// SetOwnerHours sets the "owner_hours" field.
func (_u *WorkSessionUpdateOne) SetOwnerHours(v bool) *WorkSessionUpdateOne {
	_u.mutation.SetOwnerHours(v)
	return _u
}

// SetNillableOwnerHours sets the "owner_hours" field if the given value is not nil.
func (_u *WorkSessionUpdateOne) SetNillableOwnerHours(v *bool) *WorkSessionUpdateOne {
	if v != nil {
		_u.SetOwnerHours(*v)
	}
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *WorkSessionUpdateOne) SetProject(v *Project) *WorkSessionUpdateOne {
	return _u.SetProjectID(v.ID)
}

// SetPerson sets the "person" edge to the Person entity.
func (_u *WorkSessionUpdateOne) SetPerson(v *Person) *WorkSessionUpdateOne {
	return _u.SetPersonID(v.ID)
}

// AddTaskLinkIDs adds the "task_links" edge to the WorkSessionTask entity by IDs.
func (_u *WorkSessionUpdateOne) AddTaskLinkIDs(ids ...uuid.UUID) *WorkSessionUpdateOne {
	_u.mutation.AddTaskLinkIDs(ids...)
	return _u
}

// AddTaskLinks adds the "task_links" edges to the WorkSessionTask entity.
func (_u *WorkSessionUpdateOne) AddTaskLinks(v ...*WorkSessionTask) *WorkSessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskLinkIDs(ids...)
}

// Mutation returns the WorkSessionMutation object of the builder.
func (_u *WorkSessionUpdateOne) Mutation() *WorkSessionMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *WorkSessionUpdateOne) ClearProject() *WorkSessionUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearPerson clears the "person" edge to the Person entity.
func (_u *WorkSessionUpdateOne) ClearPerson() *WorkSessionUpdateOne {
	_u.mutation.ClearPerson()
	return _u
}

// ClearTaskLinks clears all "task_links" edges to the WorkSessionTask entity.
func (_u *WorkSessionUpdateOne) ClearTaskLinks() *WorkSessionUpdateOne {
	_u.mutation.ClearTaskLinks()
	return _u
}

// RemoveTaskLinkIDs removes the "task_links" edge to WorkSessionTask entities by IDs.
func (_u *WorkSessionUpdateOne) RemoveTaskLinkIDs(ids ...uuid.UUID) *WorkSessionUpdateOne {
	_u.mutation.RemoveTaskLinkIDs(ids...)
	return _u
}

// RemoveTaskLinks removes "task_links" edges to WorkSessionTask entities.
func (_u *WorkSessionUpdateOne) RemoveTaskLinks(v ...*WorkSessionTask) *WorkSessionUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskLinkIDs(ids...)
}

// Where appends a list predicates to the WorkSessionUpdate builder.
func (_u *WorkSessionUpdateOne) Where(ps ...predicate.WorkSession) *WorkSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkSessionUpdateOne) Select(field string, fields ...string) *WorkSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WorkSession entity.
func (_u *WorkSessionUpdateOne) Save(ctx context.Context) (*WorkSession, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkSessionUpdateOne) SaveX(ctx context.Context) *WorkSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkSessionUpdateOne) check() error {
	if v, ok := _u.mutation.PayRateCents(); ok {
		if err := worksession.PayRateCentsValidator(v); err != nil {
			return &ValidationError{Name: "pay_rate_cents", err: fmt.Errorf(`ent: validator failed for field "WorkSession.pay_rate_cents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BillRateCents(); ok {
		if err := worksession.BillRateCentsValidator(v); err != nil {
			return &ValidationError{Name: "bill_rate_cents", err: fmt.Errorf(`ent: validator failed for field "WorkSession.bill_rate_cents": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkSession.project"`)
	}
	if _u.mutation.PersonCleared() && len(_u.mutation.PersonIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WorkSession.person"`)
	}
	return nil
}

func (_u *WorkSessionUpdateOne) sqlSave(ctx context.Context) (_node *WorkSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(worksession.Table, worksession.Columns, sqlgraph.NewFieldSpec(worksession.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, worksession.FieldID)
		for _, f := range fields {
			if !worksession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != worksession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StartAt(); ok {
		_spec.SetField(worksession.FieldStartAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndAt(); ok {
		_spec.SetField(worksession.FieldEndAt, field.TypeTime, value)
	}
	if _u.mutation.EndAtCleared() {
		_spec.ClearField(worksession.FieldEndAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PayRateCents(); ok {
		_spec.SetField(worksession.FieldPayRateCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPayRateCents(); ok {
		_spec.AddField(worksession.FieldPayRateCents, field.TypeInt, value)
	}
	if _u.mutation.PayRateCentsCleared() {
		_spec.ClearField(worksession.FieldPayRateCents, field.TypeInt)
	}
	if value, ok := _u.mutation.BillRateCents(); ok {
		_spec.SetField(worksession.FieldBillRateCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBillRateCents(); ok {
		_spec.AddField(worksession.FieldBillRateCents, field.TypeInt, value)
	}
	if _u.mutation.BillRateCentsCleared() {
		_spec.ClearField(worksession.FieldBillRateCents, field.TypeInt)
	}
	if value, ok := _u.mutation.OwnerHours(); ok {
		_spec.SetField(worksession.FieldOwnerHours, field.TypeBool, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   worksession.ProjectTable,
			Columns: []string{worksession.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   worksession.ProjectTable,
			Columns: []string{worksession.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PersonCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   worksession.PersonTable,
			Columns: []string{worksession.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PersonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   worksession.PersonTable,
			Columns: []string{worksession.PersonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(person.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TaskLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   worksession.TaskLinksTable,
			Columns: []string{worksession.TaskLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worksessiontask.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskLinksIDs(); len(nodes) > 0 && !_u.mutation.TaskLinksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   worksession.TaskLinksTable,
			Columns: []string{worksession.TaskLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worksessiontask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskLinksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   worksession.TaskLinksTable,
			Columns: []string{worksession.TaskLinksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(worksessiontask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WorkSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{worksession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
